### ISSUE TITLE
desktop-apps: xemacs is included twice

### ISSUE THREAD

**Issue by makohoek** [clearlinux/clr-bundles#103]
When looking at the bundles documentation, i noticed that `xemacs` is listed twice:
https://clearlinux.org/documentation/clear-linux/reference/bundles#bundles

The source file also includes it twice:
https://github.com/clearlinux/clr-bundles/blob/master/bundles/desktop-apps#L52

Is this intentional? Or should it get a clean-up patch?

**Comment by pixelgeek** [comment]
Looks like https://github.com/clearlinux/clr-bundles/blob/master/bundles/desktop-apps lines 10 and 54 are duplicates, and in https://github.com/clearlinux/clr-bundles/blob/master/bundles/os-utils-gui, lines 13 and 88.  
Assigning to @mrkz

**Comment by miguelinux** [comment]
Thanks fixed

You will see the change in the next public release
