### ISSUE TITLE
Rcpp-Armadillo in R-extras bundle not working: Armadillo library not found

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/clr-bundles#106]
In the R-extras bundle there's one R library "Rcpp-Armadillo" which requires the Armadillo c++ library. When I tried to used the Rcpp-Armadillo, it throws an error, which is resolved after I built Armadillo library by myself.

Would any one verify whether Armadillo was installed or not?

**Comment by bryteise** [comment]
@phmccarty I think is looking at a R related problems so this is probably of interest to him.

**Comment by fenrus75** [comment]
fixing this now

**Comment by phmccarty** [comment]
@bryteise The R issues I am investigating are unrelated (i.e. not related to dependency issues)

**Comment by lebensterben** [comment]
Fixed.
