### ISSUE TITLE
Package Request tensorflow_probability

### ISSUE THREAD

**Issue by stokhos** [clearlinux/clr-bundles#107]
Hi guys:
Can we add tensorflow probability package to machine-learning-tensorflow bundle? 
This package is needed in every Bayesian Neural Network model.
Would love to see it be included in machine-learning-tensorflow bundle.
https://www.tensorflow.org/probability/install
Thanks.

**Comment by fenrus75** [comment]
taking a look, it should be no harder than the other TF stuff

**Comment by fenrus75** [comment]
done; if QA passes it'll be in the afternoon release
