### ISSUE TITLE
Firefox font rendering issue

### ISSUE THREAD

**Issue by martinez314** [clearlinux/clr-bundles#11]
Since OS version 17830, Firefox is rendering fonts, including the the (default) Clear Sans font slightly distorted. Upgrading up to 17870 this evening did not fix this.
Several webpages, including Gmail and the clearlinux site itself, show this issue.
Especially, the letters n, u, i and l suffer from this issue, as it seems that their right-most pixels are not shown at all.
This is the case both on XFCE and Gnome, on 2 different PCs, on all monitors (also on laptop and attached monitor). It really seems like a Firefox issue, as the rest of the desktop environment shows fonts without problems (console, menu's, etc).
Please advise.
Best regards,
Martijn

![ff_fonts](https://user-images.githubusercontent.com/32146119/30668546-692d89ac-9e5b-11e7-8cef-161c2505dec3.png)

**Comment by bryteise** [comment]
@martinez314 Oh yikes, we'll track that down.

**Comment by mrkz** [comment]
we're aware of it (it sucks surfing the web like that and I'm affected too). so I hope we can fix fast :)

**Comment by josuedhg** [comment]
I had the same problem, using gnome-tweak-tool I just used antialiasing in standard (grayscale) and it works at least for me

**Comment by heftig** [comment]
This patch to Firefox is required to restore correct LCD rendering with 2.8.1 if the patented rendering is enabled: https://bugzilla.mozilla.org/show_bug.cgi?id=1393467

Afterwards, this patch will fix the new unpatented rendering as well: https://bugzilla.mozilla.org/show_bug.cgi?id=1400721

**Comment by martinez314** [comment]
Thank you so much for this temporary fix, as we wait for the firefox fix. (On version 17910 of ClearLinux now, things look great again).
