### ISSUE TITLE
Let's upgrade Suricata to 4.1.3 and enable jemalloc

### ISSUE THREAD

**Issue by mpurzynski** [clearlinux/clr-bundles#110]
Hey!

Let's bump Suricata from 4.1.2 to 4.1.3. It has just been released and it fixes several important issues.

While on it, may I ask for build Suricata with jemalloc support? --enable-jemalloc to the configure should do it, of course, lib and headers from jemalloc must be present.

**Comment by fenrus75** [comment]
Ill update
But eh why do you want it to go slower?

**Comment by mpurzynski** [comment]
Is jemalloc slower? I am curious - entire NSM community is raving about that.

**Comment by fenrus75** [comment]
https://www.phoronix.com/scan.php?page=news_item&px=Glibc-2.26-Redis-Test

for example

**Comment by mpurzynski** [comment]
Let's build without jemalloc for now and just do the upgrade then. I'm pretty sure the NSM community tests against CentOS 7.x and Ubuntu and they might have way slower memory allocator.
I'm pretty sure I can just LD_PRELOAD jemalloc for Suricata's performance tests. Will talk to developers first.
The 4.1.3 without jemalloc it is.

**Comment by fenrus75** [comment]
fwiw data always wins; if you can measure and show jemalloc is faster,
changed in a blink of the eye

but it's not automatically faster.... so needs measuring
