### ISSUE TITLE
Make swupd more verbose

### ISSUE THREAD

**Issue by unixbhaskar** [clearlinux/clr-bundles#14]
It would be great if I can see what is installing, rather getting a percentage output on the terminal.Is there any flag to swupd?? Not sure I missed it. 

I am getting this, which is not so helpful :(

`
Extracting desktop-gnomelibs pack for version 18060
        ...13%
Extracting dev-utils pack for version 18070
        ...15%
Extracting dev-utils-dev pack for version 18070
        ...17%
Extracting editors pack for version 18070
        ...20%
Extracting go-basic pack for version 18010
        ...22%
Extracting kernel-native pack for version 18070
        ...24%
Extracting koji pack for version 18000
        ...26%
Extracting kvm-host pack for version 18060
        ...28%
Extracting libX11client pack for version 18070
        ...31%
Extracting mixer pack for version 18000
        ...33%
Extracting network-basic pack for version 18020
        ...35%
Extracting os-clr-on-clr pack for version 18060
        ...37%
Extracting os-clr-on-clr-dev pack for version 18070
        ...40%
Extracting os-core pack for version 18080
`

**Comment by phmccarty** [comment]
@unixbhaskar Can you file an issue at https://github.com/clearlinux/swupd-client instead?

**Comment by bryteise** [comment]
This appears to be a combination issue between ister and swupd. The ister issue is https://github.com/bryteise/ister/issues/108, closing this issue.

**Comment by phmccarty** [comment]
@bryteise Ah, thanks, I didn't read the issue carefully enough.

**Comment by matthewrsj** [comment]
@bryteise I'm not seeing how this is an ister issue. Ister doesn't show percentages when installing, it shows progress dots.

**Comment by matthewrsj** [comment]
We actually have an issue open for this in swupd-client already: https://github.com/clearlinux/swupd-client/issues/255
