### ISSUE TITLE
Change  os-testsuite-graphics bundle status from "WIP" to "Active"

### ISSUE THREAD

**Issue by chiachuanwu** [clearlinux/clr-bundles#147]
As  a lot of BBT test had dependency on os-testsuite-graphics bundle we should change the status from " WIP" to "Active". Clear LTS image will only integrate "Active" bundle, in order to had BBT test coverage on Clear LTS image, we need to change os-testsuite-graphichs bundle status from "WIP" to "Active".

**Comment by phmccarty** [comment]
Fixed with ea643915457129d85af811a0c1bab87a251bb6ba
