### ISSUE TITLE
Package request (evince, libreoffice, vlc)

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/clr-bundles#15]
@unixbhaskar is requesting libreoffice, evince, and vlc via https://github.com/clearlinux/swupd-client/issues/303

**Comment by sofar** [comment]
- There's an excellent flatpak for libreoffice available.
- VLC is something we can't ship. There's a gnomeMPV flatpak that may cover the need instead.
- evince has been flatpak'd as well.
