### ISSUE TITLE
How do I know what the upstream version of a package is?

### ISSUE THREAD

**Issue by viswajithiii** [clearlinux/clr-bundles#151]
Hi!

I've been playing around a bit with `clearlinux`, and I was wondering: how do I find out what the upstream version is of a clearlinux package? If this is the wrong forum for this question, please let me know and I'm happy to ask it in the right place.

For example, I'm currently running `clearlinux` corresponding to build 30770, and I've installed `jq` with `swupd bundle-add jq`. However, there doesn't seem to be a way for me to know what version of `jq` (from their [GitHub](https://github.com/stedolan/jq/releases)) this binary actually contains.

When I run `jq --help` to see what version is running, it just emits a `-`:
```
sh-5.0# jq --help
jq - commandline JSON processor [version -]
```
(For reference, on my Mac, it prints `jq - commandline JSON processor [version 1.6]`.)

Is there a way for me to find out? I've tried perusing the files in this repo, but I couldn't see any version information. I presume there is some code that crawls GitHub, builds clearlinux binaries, and adds them to the swupd manifests, but I don't know where it is.

Thank you!

**Comment by fenrus75** [comment]
$ swupd search jq
Component jq has version 1.6

Bundle with the best search result:
     jq                                 - Lightweight and flexible
command-line JSON processor.  (1MB) (installed)

This bundle can be installed with:

  swupd bundle-add  jq

**Comment by fenrus75** [comment]
another good resource is our packages github, e.g.

https://github.com/clearlinux-pkgs/jq/blob/master/upstream
