### ISSUE TITLE
DGA?

### ISSUE THREAD

**Issue by 10010101001** [clearlinux/clr-bundles#153]
I need x11 DGA to compile a quake 3 source port called q3e, where can I get it?

**Comment by fenrus75** [comment]
have you tried the games-dev bundle? it has libXxf86dga-dev at least and
likely many other things games need to build

**Comment by 10010101001** [comment]
It worked, thanks.

**Comment by 10010101001** [comment]
It worked, thanks.

**Comment by 10010101001** [comment]
It worked, thanks.
