### ISSUE TITLE
php-extras php-imagick unable to load undefined symbol: FT_Done_MM_Var)

### ISSUE THREAD

**Issue by ketonik** [clearlinux/clr-bundles#157]
Trying to load the "imagick" extension in PHP.

`php -i`  reports:

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick.so' (tried: /usr/lib64/extensions/no-debug-non-zts-20180731/imagick.so 
(/usr/lib64/haswell/libharfbuzz.so.0: undefined symbol: FT_Done_MM_Var), 
/usr/lib64/extensions/no-debug-non-zts-20180731/imagick.so.so 
(/usr/lib64/extensions/no-debug-non-zts-20180731/imagick.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

phpinfo()
PHP Version => 7.3.9

My PHP ini file:

`/etc/php.d/php.ini`

```
[zendopcache]
extension = apcu.so
extension = redis.so
extension = imagick.so
opcache.memory_consumption=256
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=4000
opcache.revalidate_freq=180
opcache.fast_shutdown=1
opcache.enable_cli=0
opcache.enable=0
opcache.huge_code_pages=1
max_execution_time = 300
max_input_time = 1000
upload_max_filesize = 150M
post_max_size = 150M
```

**Comment by ketonik** [comment]
More a question than issue, will php-imagick be linked to libjpeg-turbo if bundle devpkg-libjpeg-turbo is installed?

**Comment by bryteise** [comment]
In Clear Linux, libjpeg turbo is the libjpeg.

**Comment by ketonik** [comment]
> In Clear Linux, libjpeg turbo is the libjpeg.

Positive on that?
Clear Linux is using this https://libjpeg-turbo.org

gd in php is definitely using **libjpeg-turbo**??

![Screen Shot 2019-10-01 at 00 56 34](https://user-images.githubusercontent.com/49221849/65899515-7bc4f780-e3e6-11e9-97dd-4c8e36cd4dfb.png)

**Comment by bryteise** [comment]
As for the bug, looks like libfreetype isn't part of the dependency chain for the php-imagick package causing the overall bug.

**Comment by bryteise** [comment]
Hrm I'd have to look if php is bundling their own libjpeg I guess but /usr/lib64/libjpeg.so [is](https://github.com/clearlinux-pkgs/libjpeg-turbo/blob/master/libjpeg-turbo.spec#L270).

**Comment by bryteise** [comment]
No php links against the system libjpeg.

**Comment by ketonik** [comment]
> No php links against the system libjpeg.

Right, thanks for confirm. 

The future, can we ensure php links against:
`libjpeg-turbo`

This will give us valuable server side image processing advantages, less load on CPU and faster processing times overall allowing more users to be served faster, reducing our progress spinners.

**Comment by bryteise** [comment]
No I mean it is using libjpeg turbo which is the system libjpeg. /usr/lib64/libjpeg.so is the emulation layer that handles the libjpeg api for libjpeg turbo.

**Comment by ketonik** [comment]
Ok so are there any known measured overheads using an emulation layer? Doesn't sound ideal at first thought.

**Comment by bryteise** [comment]
I'm not aware of any performance differences and a quick search didn't show anything of that caught my eye. It is doing the same thing either way, just the calling convention is different from my understanding.

**Comment by ketonik** [comment]
https://libjpeg-turbo.org/About/Performance

**Comment by bryteise** [comment]
So maybe I'm reading that wrong, but it says it is measuring the emulation layers built against libjpeg (because the benchmark program only knows the turbo version api) so that isn't testing the emulation layer using libjpeg-turbo.

**Comment by ketonik** [comment]
Thanks for all your commentary on helping us understand the situation.

**Comment by bryteise** [comment]
No problem, I got to learn a few things about the benchmark program while I was at it =).
