### ISSUE TITLE
firewalld bundle is missing a python dependency 

### ISSUE THREAD

**Issue by electrocucaracha** [clearlinux/clr-bundles#159]
Hey there, 

I was updating one of my scripts for adding support to CLR and I noticed that this dependency is not included in the `firewalld` bundle. I couldn't find its requirements.txt file in their repo so I'm not sure about the exact python module required by this project but hopefully the following link helps to get an idea:

* https://github.com/firewalld/firewalld/blob/master/src/firewall-cmd.in

```bash
clear@clearlinux ~ $ sudo swupd info
Distribution:      Clear Linux OS
Installed version: 31130
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update
clear@clearlinux ~ $ sudo -H -E swupd bundle-add --quiet firewalld
Successfully installed 1 bundle
clear@clearlinux ~ $ firewall-cmd 
Traceback (most recent call last):
  File "/usr/bin/firewall-cmd", line 24, in <module>
    from gi.repository import GObject
ModuleNotFoundError: No module named 'gi'
```

**Comment by bryteise** [comment]
Thanks for the report, updated firewalld to require missing bits (pygobject and dbus-python in this case).
