### ISSUE TITLE
PHP Warning:  PHP Startup: Unable to load dynamic library 'blackfire.so'

### ISSUE THREAD

**Issue by ketonik** [clearlinux/clr-bundles#160]
I have PHP 7.3.10, current as of now. Have a requirement to install Blackfire to profile my Symfony App.

I performed a manual installation:

https://blackfire.io/docs/up-and-running/installation

`https://packages.blackfire.io/binaries/blackfire-agent/1.27.4/blackfire-agent-linux_amd64`

dropped the blackfire-agent into `/usr/local/bin`

Downloaded the PHP Probe:

https://packages.blackfire.io/binaries/blackfire-php/1.27.1/blackfire-php-linux_amd64-php-73-zts.so

Dumped the PHP Probe into:

/usr/lib64/extensions/no-debug-non-zts-20180731/

Added `extension=blackfire.so` to my php.ini file in /etc/php.d/

Ran

`php -i | grep 'extension_dir'`

Received output:

`PHP Warning:  PHP Startup: Unable to load dynamic library 'blackfire.so'`

` (tried: /usr/lib64/extensions/no-debug-non-zts-20180731/blackfire.so `

`(/usr/lib64/extensions/no-debug-non-zts-20180731/blackfire.so: `

`undefined symbol: sapi_globals_id), /usr/lib64/extensions/no-debug-non-zts-20180731/blackfire.so.so `

`(/usr/lib64/extensions/no-debug-non-zts-20180731/blackfire.so.so: `

`cannot open shared object file: No such file or directory)) in Unknown on line 0`

`extension_dir => /usr/lib64/extensions/no-debug-non-zts-20180731 => /usr/lib64/extensions/no-debug-non-zts-20180731`

Anyone have any ideas on how to resolve?

Cheers

**Comment by ketonik** [comment]
I mistakenly installed a ZTS version of the Blackfire PHP Probe extension instead of non-ZTS.

**Comment by Flinsch** [comment]
> I mistakenly installed a ZTS version of the Blackfire PHP Probe extension instead of non-ZTS.

Same! But exactly the other way round. :joy::kissing_heart: Thank you for your own feedback on the solution! That helped me. :+1:
