### ISSUE TITLE
Where is 'pcap.h'

### ISSUE THREAD

**Issue by AWHubGit** [clearlinux/clr-bundles#161]
sudo swupd search-file pcap.h
Searching for 'pcap.h'
Bundle devpkg-libpcap (3 MB to install)
	/usr/include/pcap/pcap.h
	/usr/include/pcap.h
sudo swupd bundle-add devpkg-libcap
1 bundle was already installed

sudo ls /usr/include/ -all
insgesamt 3936
drwxr-xr-x 46 root root    4096  9. Okt 19:00 .
drwxr-xr-x 13 root root    4096 20. Jul 10:15 ..
-rw-r--r--  1 root root    7456 14. Jan 2017  aio.h
 .....................................
-rw-r--r--  1 root root   21306 14. Jan 2017  obstack.h
-rw-r--r--  1 root root    4577  1. Feb 2019  openblas_config.h
-rw-r--r--  1 root root    3032 14. Jan 2017  paths.h
-rw-r--r--  3 root root   15029  3. Feb 2019  plugin-api.h
-rw ..............................

No pcap.h in /usr/include/ after installation of devpkg-libcap. Why?

**Comment by phmccarty** [comment]
@AWHubGit Looks like you installed `devpkg-libcap` instead of `devpkg-libpcap`. Those two bundles install different content.

**Comment by AWHubGit** [comment]
I am sorry: It was a sunny morning today and not the right time to sit behind my computer compiling funny things.
