### ISSUE TITLE
Bundle Suggestions

### ISSUE THREAD

**Issue by trpg1** [clearlinux/clr-bundles#168]
Syntax: Binary Package (Bundle1) (Bundle2)

qterminal (desktop-lxqt)
lximage-qt (desktop-lxqt)
obconf-qt (desktop-lxqt)
screengrab (desktop-lxqt)
chromium (chromium)
pepper-flash (chromium)
chromium-widevine (chromium)
midori (midori)
opera (opera)
vivaldi (vivaldi)
epiphany (epiphany)
brave (brave-browser)
gufw (gufw)

**Comment by lebensterben** [comment]
Package request should go to clearlinux/distribution repo. And in general you need to create one issue for each package you requested for ease of tracking.

**Comment by bryteise** [comment]
In general Clear Linux would not be distributing binary content itself via native bundles. This would be a good list for the community to be able to provide especially once 3rd-party bundle creation is enabled.
