### ISSUE TITLE
Remove python3-basic and uwsgi from pxe-server bundle

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clr-bundles#171]
Please remove these:

include(python3-basic)
include(uwsgi)

from the `pxe-server` because they are no longer needed for with the new implementation of PXE.  
New PXE implementation deprecates ister and ucd.  These 2 includes were needed for ucd.  

Thanks!

**Comment by bryteise** [comment]
Are the new PXE images released with documentation on their usage?

**Comment by mvincerx** [comment]
[Revision to original ipxe-install doc](https://github.com/clearlinux/clear-linux-documentation/pull/932) is in progress:
See [this section](https://github.com/clearlinux/clear-linux-documentation/blob/bafcc5442100073ebb3653a872c57b3c6f8c8c93/source/get-started/ipxe-install.rst#configure-ipxe) for reference to new `pxe` tar file.

**Comment by bktan8** [comment]
@bryteise - New PXE doc and image published.  You can proceed with updating pxe-server bundle.  Thanks!

**Comment by mvincerx** [comment]
Yep. I just published minutes ago: https://docs.01.org/clearlinux/latest/get-started/ipxe-install.html

**Comment by bryteise** [comment]
This is done.
