### ISSUE TITLE
Would it be possible to add libncurses 5 to the devpkg ncurses bundle?

### ISSUE THREAD

**Issue by ZVNexus** [clearlinux/clr-bundles#179]
Trying to set up a bundle for AOSP development but AOSP still depends on legacy versions of ncurses. Symlinking 6 to 5 works but I would rather not have to do that.

**Comment by fenrus75** [comment]
does it compile against it, or is it just using binaries that use it?
in case of just using it.. we have a special (relatively small) bundle with
a few compat libs like this

**Comment by ZVNexus** [comment]
> Does it compile against it, or is it just using binaries that use it? in case of just using it, we have a special (relatively small) bundle with a few compat libs like this.

prebuilts/clang/host/linux-x86/clang-3289846/bin/clang.real: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
prebuilts/clang/host/linux-x86/clang-3289846/bin/clang.real: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory

So it just appears to be a library that Clang 3.8 uses.

**Comment by fenrus75** [comment]
this should be in the "compat-common" bundle

**Comment by fenrus75** [comment]
(unless this is a 32 bit clang)

**Comment by ZVNexus** [comment]
Ah alrighty it appears compat-common serves my purposes. Thanks!
