### ISSUE TITLE
can't get libva.so.1, libva-x11.so.1and libva-drm.so.1

### ISSUE THREAD

**Issue by tuxutku** [clearlinux/clr-bundles#21]
i am trying to get those files:
libva.so.1
libva-x11.so.1
libva-drm.so.1

And those files exist:

utku@clr-449e9b2a44f8458bb4885604dc172a1c ~ $ find /usr -name libva*
/usr/lib64/libva-x11.so
/usr/lib64/libva.so
/usr/lib64/libva-x11.so.2.0.0
/usr/lib64/libva-drm.so.2.0.0
/usr/lib64/libva.so.2
/usr/lib64/totem/plugins/variable-rate/libvariable-rate.so
/usr/lib64/libva-drm.so
/usr/lib64/libva-wayland.so
/usr/lib64/libva-glx.so.2.0.0
/usr/lib64/libva-drm.so.2
/usr/lib64/libva-wayland.so.2.0.0
/usr/lib64/libva-glx.so.2
/usr/lib64/libva-wayland.so.2
/usr/lib64/libva.so.2.0.0
/usr/lib64/pkgconfig/libva-wayland.pc
/usr/lib64/pkgconfig/libva-glx.pc
/usr/lib64/pkgconfig/libva.pc
/usr/lib64/pkgconfig/libva-drm.pc
/usr/lib64/pkgconfig/libva-x11.pc
/usr/lib64/libva-glx.so
/usr/lib64/libva-x11.so.2

Also there is a issue that i am trying to compile libav and install it to /usr/local:
https://github.com/01org/intel-vaapi-driver/issues/303

**Comment by seanvk** [comment]
You are trying to manually build an older version of libva which is not supported.  On top of that you are trying to have it coexist with the Clear version of libva.  Do I have that correctly?

**Comment by tuxutku** [comment]
>You are trying to manually build an older version of libva which is not supported. On top of that you are trying to have it coexist with the Clear version of libva. Do I have that correctly?

i did compiled libva back then, but i have removed clear linux and installed antergos instead, was installed clear linux for learning purpose and it teach me a lot
