### ISSUE TITLE
Is SVT-AV1 bundle maintained?

### ISSUE THREAD

**Issue by tixoi** [clearlinux/clr-bundles#210]
Hello,
is SVT-AV1 bundle still actively maintained?
The bundle is several major versions behind...

thank you for the answer

**Comment by fenrus75** [comment]
hmm for some reason our scanner for newer versions did not pick up newer
versions

updating now, but also we'll check our scanner for why this happened

**Comment by tixoi** [comment]
May I ask the same question about the SVT-HEVC bundle here, or should I start a new issue?

**Comment by fenrus75** [comment]
I alreay just checked that as a result of your first question, with
basically the same answer; the scanner missed it
and I did a manual update, now need to still debug the scanner

**Comment by phmccarty** [comment]
The latest version of SVT-HEVC *was* detected correctly. However, SVT-AV1 was not, due to all of the tagged releases being marked "pre-release". I added an override to permit scanning of pre-releases for SVT-AV1.

**Comment by tixoi** [comment]
Thank you very much for fixing so quickly.
What is the right way to report issues of the kind - I've noticed some more outdated packages (mediasdk intel-media-driver libva libva-intel-driver)?
How can I contibute to
_make Clear Linux up to date again? :-)_

**Comment by phmccarty** [comment]
@tixoi You can report packages as out-of-date by opening an issue at https://github.com/clearlinux/distribution/issues. Use the "Package update" template to make it easier for us to track.
