### ISSUE TITLE
file roller broke after update

### ISSUE THREAD

**Issue by tuxutku** [clearlinux/clr-bundles#22]
after updating version from 19120 to 19420, installed file roller is broken
Note: am i have to post update issues to this repository or swupd-client

<pre>
utku@clr-449e9b2a44f8458bb4885604dc172a1c ~ $ file-roller -v
file-roller 3.10.0, Copyright © 2001-2012 Free Software Foundation, Inc.
utku@clr-449e9b2a44f8458bb4885604dc172a1c ~ $ file-roller

(file-roller:9576): GLib-GIO-ERROR **: Settings schema 'org.gnome.FileRoller.UI' does not contain a key named 'view-folders'
Trace/breakpoint trap (core dumped)
utku@clr-449e9b2a44f8458bb4885604dc172a1c ~ $ ls /usr/share/glib-2.0/schemas
10_gnome_settings.gschema.override
gschema.dtd
gschemas.compiled
net.connman.gtk.gschema.xml
org.freedesktop.ColorHelper.gschema.xml
org.freedesktop.ibus.gschema.xml
org.freedesktop.Telepathy.Logger.gschema.xml
org.freedesktop.Tracker.DB.gschema.xml
org.freedesktop.Tracker.enums.xml
org.freedesktop.Tracker.gschema.xml
org.freedesktop.Tracker.Store.gschema.xml
org.gnome.antler.gschema.xml
org.gnome.calculator.gschema.xml
org.gnome.calendar.enums.xml
org.gnome.calendar.gschema.xml
org.gnome.caribou.gschema.xml
org.gnome.Characters.gschema.xml
org.gnome.Cheese.gschema.xml
org.gnome.crypto.cache.gschema.xml
org.gnome.crypto.pgp.gschema.xml
org.gnome.desktop.a11y.applications.gschema.xml
org.gnome.desktop.a11y.gschema.xml
org.gnome.desktop.a11y.keyboard.gschema.xml
org.gnome.desktop.a11y.magnifier.gschema.xml
org.gnome.desktop.a11y.mouse.gschema.xml
org.gnome.desktop.app-folders.gschema.xml
org.gnome.desktop.background.gschema.xml
org.gnome.desktop.calendar.gschema.xml
org.gnome.desktop.datetime.gschema.xml
org.gnome.desktop.default-applications.gschema.xml
org.gnome.desktop.enums.xml
org.gnome.desktop.input-sources.gschema.xml
org.gnome.desktop.interface.gschema.xml
org.gnome.desktop.lockdown.gschema.xml
org.gnome.desktop.media-handling.gschema.xml
org.gnome.desktop.notifications.gschema.xml
org.gnome.desktop.peripherals.gschema.xml
org.gnome.desktop.privacy.gschema.xml
org.gnome.desktop.screensaver.gschema.xml
org.gnome.desktop.search-providers.gschema.xml
org.gnome.desktop.session.gschema.xml
org.gnome.desktop.sound.gschema.xml
org.gnome.desktop.thumbnail-cache.gschema.xml
org.gnome.desktop.thumbnailers.gschema.xml
org.gnome.desktop.wm.keybindings.gschema.xml
org.gnome.desktop.wm.preferences.gschema.xml
org.gnome.eog.enums.xml
org.gnome.eog.gschema.xml
org.gnome.eog.plugins.exif-display.gschema.xml
org.gnome.eog.plugins.export-to-folder.gschema.xml
org.gnome.eog.plugins.fullscreenbg.gschema.xml
org.gnome.eog.plugins.pythonconsole.gschema.xml
org.gnome.Evince.gschema.xml
org.gnome.evolution.addressbook.gschema.xml
org.gnome.evolution.bogofilter.gschema.xml
org.gnome.evolution.calendar.gschema.xml
org.gnome.evolution-data-server.addressbook.gschema.xml
org.gnome.evolution-data-server.calendar.gschema.xml
org.gnome.evolution-data-server.gschema.xml
org.gnome.Evolution.DefaultSources.gschema.xml
org.gnome.evolution.eds-shell.gschema.xml
org.gnome.evolution.gschema.xml
org.gnome.evolution.importer.gschema.xml
org.gnome.evolution.mail.gschema.xml
org.gnome.evolution.plugin.attachment-reminder.gschema.xml
org.gnome.evolution.plugin.autocontacts.gschema.xml
org.gnome.evolution.plugin.email-custom-header.gschema.xml
org.gnome.evolution.plugin.external-editor.gschema.xml
org.gnome.evolution.plugin.face-picture.gschema.xml
org.gnome.evolution.plugin.itip.gschema.xml
org.gnome.evolution.plugin.mail-notification.gschema.xml
org.gnome.evolution.plugin.prefer-plain.gschema.xml
org.gnome.evolution.plugin.publish-calendar.gschema.xml
org.gnome.evolution.plugin.templates.gschema.xml
org.gnome.evolution.shell.gschema.xml
org.gnome.evolution.shell.network-config.gschema.xml
org.gnome.evolution.spamassassin.gschema.xml
org.gnome.evolution.text-highlight.gschema.xml
org.gnome.FileRoller.gschema.xml
org.gnome.gedit.enums.xml
org.gnome.gedit.gschema.xml
org.gnome.gedit.plugins.externaltools.gschema.xml
org.gnome.gedit.plugins.filebrowser.enums.xml
org.gnome.gedit.plugins.filebrowser.gschema.xml
org.gnome.gedit.plugins.pythonconsole.gschema.xml
org.gnome.gedit.plugins.time.enums.xml
org.gnome.gedit.plugins.time.gschema.xml
org.gnome.gnome-applets.battstat.gschema.xml
org.gnome.gnome-applets.charpick.gschema.xml
org.gnome.gnome-applets.command.gschema.xml
org.gnome.gnome-applets.geyes.gschema.xml
org.gnome.gnome-applets.gweather.gschema.xml
org.gnome.gnome-applets.invest.gschema.xml
org.gnome.gnome-applets.multiload.gschema.xml
org.gnome.gnome-applets.netspeed.gschema.xml
org.gnome.gnome-applets.stickynotes.gschema.xml
org.gnome.gnome-applets.timer.gschema.xml
org.gnome.gnome-applets.window-buttons.gschema.xml
org.gnome.gnome-applets.window-title.gschema.xml
org.gnome.gnome-flashback.desktop-background.gschema.xml
org.gnome.gnome-flashback.gschema.xml
org.gnome.gnome-flashback.input-sources.gschema.xml
org.gnome.gnome-flashback.workarounds.gschema.xml
org.gnome.gnome-panel.applet.clock.gschema.xml
org.gnome.gnome-panel.applet.fish.gschema.xml
org.gnome.gnome-panel.applet.window-list.gschema.xml
org.gnome.gnome-panel.applet.workspace-switcher.gschema.xml
org.gnome.gnome-panel.enums.xml
org.gnome.gnome-panel.gschema.xml
org.gnome.gnome-panel.launcher.gschema.xml
org.gnome.gnome-panel.menu-button.gschema.xml
org.gnome.gnome-panel.object.gschema.xml
org.gnome.gnome-panel.toplevel.gschema.xml
org.gnome.gnome-screenshot.gschema.xml
org.gnome.GWeather.enums.xml
org.gnome.GWeather.gschema.xml
org.gnome.libgnomekbd.desktop.gschema.xml
org.gnome.libgnomekbd.gschema.xml
org.gnome.libgnomekbd.keyboard.gschema.xml
org.gnome.login-screen.gschema.xml
org.gnome.metacity.gschema.xml
org.gnome.metacity.keybindings.gschema.xml
org.gnome.metacity.theme.gschema.xml
org.gnome.mutter.gschema.xml
org.gnome.mutter.wayland.gschema.xml
org.gnome.nautilus.gschema.xml
org.gnome.nm-applet.gschema.xml
org.gnome.online-accounts.gschema.xml
org.gnome.seahorse.recipients.gschema.xml
org.gnome.SessionManager.gschema.xml
org.gnome.settings-daemon.enums.xml
org.gnome.settings-daemon.peripherals.gschema.xml
org.gnome.settings-daemon.peripherals.wacom.gschema.xml
org.gnome.settings-daemon.plugins.color.gschema.xml
org.gnome.settings-daemon.plugins.gschema.xml
org.gnome.settings-daemon.plugins.housekeeping.gschema.xml
org.gnome.settings-daemon.plugins.media-keys.gschema.xml
org.gnome.settings-daemon.plugins.power.gschema.xml
org.gnome.settings-daemon.plugins.sharing.gschema.xml
org.gnome.settings-daemon.plugins.xsettings.gschema.xml
org.gnome.shell.extensions.auto-move-windows.gschema.xml
org.gnome.shell.extensions.example.gschema.xml
org.gnome.shell.extensions.native-window-placement.gschema.xml
org.gnome.shell.extensions.screenshot-window-sizer.gschema.xml
org.gnome.shell.extensions.user-theme.gschema.xml
org.gnome.shell.extensions.window-list.gschema.xml
org.gnome.shell.gschema.xml
org.gnome.system.gvfs.enums.xml
org.gnome.system.locale.gschema.xml
org.gnome.system.location.gschema.xml
org.gnome.system.proxy.gschema.xml
org.gnome.system.smb.gschema.xml
org.gnome.Terminal.gschema.xml
org.gnome.totem.enums.xml
org.gnome.totem.gschema.xml
org.gnome.totem.plugins.opensubtitles.gschema.xml
org.gnome.totem.plugins.pythonconsole.gschema.xml
org.gnome.Vinagre.gschema.xml
org.gtk.Demo.gschema.xml
org.gtk.exampleapp.gschema.xml
org.gtk.Settings.ColorChooser.gschema.xml
org.gtk.Settings.Debug.gschema.xml
org.gtk.Settings.EmojiChooser.gschema.xml
org.gtk.Settings.FileChooser.gschema.xml
org.virt-manager.virt-manager.gschema.xml
utku@clr-449e9b2a44f8458bb4885604dc172a1c ~ $ sudo swupd bundle-list
swupd-client bundle list 3.14.1
   Copyright (C) 2012-2017 Intel Corporation

R-basic
bootloader
c-basic
clr-devops
cryptography
database-basic
desktop
desktop-apps
desktop-apps-extras
desktop-assets
desktop-autostart
desktop-dev
desktop-gnomelibs
desktop-locales
dev-utils
dev-utils-dev
editors
editors-dev
games
games-dev
go-basic
java-basic
kernel-native
koji
kvm-host
libX11client
machine-learning-basic
mail-utils
mail-utils-dev
mixer
network-basic
network-basic-dev
openssh-server
os-clr-on-clr
os-core
os-core-dev
os-core-update
os-core-update-dev
os-installer
os-testsuite
os-testsuite-phoronix
os-utils-gui
os-utils-gui-dev
perl-basic
perl-basic-dev
php-basic
python-basic
python-basic-dev
python-extras
python3-basic
ruby-basic
rust-basic
shells
storage-utils
storage-utils-dev
sysadmin-basic
sysadmin-basic-dev
telemetrics
user-basic
user-basic-dev
web-server-basic
xfce4-desktop
Current OS version: 19420
utku@clr-449e9b2a44f8458bb4885604dc172a1c ~ $ uname -a
Linux clr-449e9b2a44f8458bb4885604dc172a1c 4.14.3-482.native #2 SMP Thu Nov 30 12:15:31 UTC 2017 x86_64 GNU/Linux
</pre>

**Comment by tuxutku** [comment]
Here is the issues that update specific but i didn't knew where to post
https://github.com/clearlinux/swupd-client/issues/345
https://github.com/clearlinux/swupd-client/issues/346

**Comment by mrkz** [comment]
Couldn't reproduce, If you are still experiencing issues, please re-open or push a new bug.
Thanks!
