### ISSUE TITLE
Snap support?

### ISSUE THREAD

**Issue by RDKRACZ** [clearlinux/clr-bundles#228]
I see flatpak is supported but seems like snap is not (not in any bundle). I need it to install brave browser (`sudo snap install brave`). Sadly brave doesn't support  flatpak.

**Comment by pixelgeek** [comment]
We have no plans for snap support.  
If you want to install Brave, the Clear Linux community has a couple of options for you to try - 
[MattiaVerticchio](https://community.clearlinux.org/u/MattiaVerticchio) has a [script ](https://community.clearlinux.org/t/installing-brave-browser-on-clear-linux/1131)to install Brave, or maybe easier [paulcarroty](https://community.clearlinux.org/u/paulcarroty) has set up a [3rd party repo](https://clearfraction.cf/) which includes Brave
