### ISSUE TITLE
cifs-utils no vers=3.0 support?

### ISSUE THREAD

**Issue by Andy2244** [clearlinux/clr-bundles#24]
I cant mount a windows 10 share via: `mount.cifs ... -o vers=3.0`
i get a : `mount error(22): Invalid argument` ?

If i use `vers=1.0` than i get: `mount error(112): Host is down`

Is the kernel build with smb 3.0 cifs support and the cifs-utils as well?
Windows 10 uses SMB 3.1.1 by default and getting SMB 1.0 to work requires to enable the old "SMB 1.0" feature, which is not recommend anymore.

So why cant i mount a normal windows 10 share into clear linux?

PS: I'm using kernel `Linux clear-vm 4.12.10-118.hyperv `

**Comment by bryteise** [comment]
@miguelinux Any ideas for this?

**Comment by Andy2244** [comment]
I think he was just about to add the kernel options (what he told me in irc) <4.12=CONFIG_CIFS_SMB2 and CONFIG_CIFS_SMB311 for >4.14, so should be done soon i guess.
