### ISSUE TITLE
Why does installing firewalld install mesa?

### ISSUE THREAD

**Issue by FallingSnow** [clearlinux/clr-bundles#240]
I installed `dnf` using https://docs.01.org/clearlinux/latest/guides/maintenance/query-upstream.html?highlight=dnf#configure-dnf.

I went to install `firewalld` but was greeted with the following.
```
Installing:
 firewalld      x86_64     1.2.1-36       clear        62 k
Installing dependencies:
...
Install  140 Packages

Total download size: 175 M
Installed size: 735 M
```

I don't know if I'm missing something but it seems a little ridiculous that a 62k package requires __175M of dependencies__. Firewalld only lists the following dependencies.
```
  linux >= 5.3
  python3-dbus
  python3-gobject
  python3-nftables >= 0.9.4
```

And no linux is not one of the dependencies listed in the `Installing dependencies:` above, however `mesa` is...?

**Comment by fenrus75** [comment]
Clear Linux isn't an rpm/dnf based distribution right now

however it's likely that a full firewalld bundle wouldn't be different..
I'll check

However the requirements you list aren't from us


(It also can be that you get the GUI part of firewalld included.. again
I'll check)

**Comment by FallingSnow** [comment]
Thanks for getting back to me so quickly.

I actually installed dnf because I figured the `swupd bundle-add` installer was what was causing these huge install sizes. It seems that was not the case.

> (It also can be that you get the GUI part of firewalld included.. again I'll check)

I think that is the case. Some of the dependencies it is pulling are `wayland-...`.

**Comment by fenrus75** [comment]
ok the plot thickens
        pygobject-python3 = 3.42.2-70 is needed by (installed)
pygobject-3.42.2-70.x86_64
        libcairo.so.2()(64bit) is needed by (installed)
pygobject-python3-3.42.2-70.x86_64
        libGL.so.1()(64bit) is needed by (installed)
cairo-lib-1.16.0-83.x86_64

so python-gobject pulls in cairo, which pulls in mesa.

**Comment by fenrus75** [comment]
the pygobject->cairo->mesa chain isn't going to be an easy one to break
unfortunately.

**Comment by FallingSnow** [comment]
I see. Okay well I guess it is what it is. Thanks for looking into it.

**Comment by fenrus75** [comment]
we retooled our packaging tooling to allow the pygobject package to be
split so this should be resolved in the latest release (hopefully coming
out today)

**Comment by FallingSnow** [comment]
Awesome! Thank you!
