### ISSUE TITLE
pkg-request: wlroots

### ISSUE THREAD

**Issue by godalming123** [clearlinux/clr-bundles#245]
Would it be possible to  have a wlroots package this would make it much easy to build almost all wayland WM's instead of having to create separate bundles for them.

**Comment by godalming123** [comment]
If anyone would be willing to help me make a wlroots package I would be willing to do that

**Comment by fenrus75** [comment]
before us humans spend time..
let me see what happens if we feed this to our automation... since if the
automation can package it then maintenance is a lot more efficient for us

**Comment by fenrus75** [comment]
(fwiw our automation takes an url to a release tar file as input)

**Comment by godalming123** [comment]
Do you want me to provide a URL?

**Comment by godalming123** [comment]
When will I be able to use this?

**Comment by godalming123** [comment]
@fenrus75 if/when you add this will it include the development packages, since I want to compile dwl I need these so if not then I wouldn't use this unless I can also install the development packages as well

**Comment by fenrus75** [comment]
# swupd bundle-add devpkg-wlroots
Loading required manifests...
Downloading packs (11.00 MB) for:
 - devpkg-wlroots


seems to work for me

**Comment by godalming123** [comment]
For some reason I could not find wlroots by searching on the website or with:
```
swupd search wlroots
```
But now that I can install the package, yes it works.
