### ISSUE TITLE
Solaar not working

### ISSUE THREAD

**Issue by Aqua1ung** [clearlinux/clr-bundles#249]
Looks like Solaar bundles were added recently (may thanks!), though so far I have not been able to make Solaar work due to a permissions issue that doesn't seem to go away no matter what. Would you guys mind looking into that please!

![Screenshot from 2023-05-11 12-08-13](https://github.com/clearlinux/clr-bundles/assets/12104779/f6ac2e8a-c392-4976-8c23-6c7655b2ff7c).

**Comment by greysonofusa** [comment]
I remember the fix for this issue. Run as sudo from CLI
