### ISSUE TITLE
Add cockpit-project.org ?

### ISSUE THREAD

**Issue by Andy2244** [clearlinux/clr-bundles#25]
As a cloud/container focused linux os, it would be great to get cockpit ui working with clearlinux. www.projectatomic.io has it build in and i just tested it there and was impressed how nice the server + container management works with it.

So maybe consider adding it to the sysadmin-remote-managed bundle or make a separate?

**Comment by bryteise** [comment]
Ah I haven't run that before but we can see about adding it.

**Comment by Andy2244** [comment]
As i have mentioned in the irc chat, it seems cockpit just needs the "bridge" service running on a system and the web service can/should be installed as a [container](https://hub.docker.com/r/cockpit/ws/).

**Comment by bryteise** [comment]
Hrm this seems to want to pull in python2 which I'm not going to do. It looks like something hard codes /usr/bin/python2 somewhere so it may be awhile to figure out if this can be patched easily or not.

**Comment by Andy2244** [comment]
I'm confused, the '/usr/bin/python2' statements are all in /tools and /test, which are not needed to either run/compile the server component (socket, bridge) and the webserver seems to-be created as container for docker/kubernetes. At least thats how Atomic seems to use cockpit.

What do you mean by "Hrm this seems to want to pull in python2 which I'm not going to do." ? A quick look at the git statements seem to indicate that they recently switched to python3 or at least are in transition, but thats only for the test/tools part. So whats the problem letting it use python2 for the build/test part?

**Comment by bryteise** [comment]
Normally we like to have the tests run but if it is just the tests I can probably just skip them for this and just rely on the QA tests. I'd guess they are only in transition in the conversion. I'll make a reminder to myself to try out running the tests again in a few months. In the meantime I have it packaged.

**Comment by bryteise** [comment]
This should be available in sysadmin-remote bundle in the afternoon release.

**Comment by Andy2244** [comment]
cool thx for the quick work, can't wait to test this more in-depth and see if it can replace portainer.

**Comment by Andy2244** [comment]
TLS support is missing see: https://github.com/cockpit-project/cockpit/issues/3927

root@clear-vm ~ # remotectl  certificate
remotectl: Error loading certificates from /usr/share/xdg/cockpit/ws-certs.d: Error opening directory ?/usr/share/xdg/cockpit/ws-certs.d?: No such file or directory
root@clear-vm ~ # journalctl -fu cockpit
-- Logs begin at Tue 2017-12-12 17:45:45 CET. --
clear-vm systemd[1]: cockpit.service: Failed with result 'exit-code'.
clear-vm systemd[1]: Starting Cockpit Web Service...
clear-vm remotectl[870]: remotectl: /etc/cockpit/ws-certs.d/0-self-signed.cert: TLS support is not available
clear-vm systemd[1]: cockpit.service: Control process exited, code=exited status=1
clear-vm systemd[1]: Failed to start Cockpit Web Service.
clear-vm systemd[1]: cockpit.service: Unit entered failed state.
clear-vm systemd[1]: cockpit.service: Failed with result 'exit-code'.
clear-vm systemd[1]: cockpit.service: Start request repeated too quickly.
clear-vm systemd[1]: Failed to start Cockpit Web Service.
clear-vm systemd[1]: cockpit.service: Failed with result 'exit-code'.

I also had to manually create the /etc/cockpit/ws-certs.d/ , not sure if this is normal.

**Comment by bryteise** [comment]
Added glib-networking as a cockpit runtime requirement.

**Comment by Andy2244** [comment]
oki now i can get to the login screen, but than the logins fails.
```
clear-vm cockpit-ws[36230]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
clear-vm cockpit-session[36237]: pam_warn(cockpit:auth): function=[pam_sm_authenticate] flags=0 service=[cockpit] terminal=[<unknown>] user=[root] ruser=[<unknown>] rhost=[192.168.1.101]
clear-vm cockpit-session[36238]: pam_warn(cockpit:auth): function=[pam_sm_authenticate] flags=0 service=[cockpit] terminal=[<unknown>] user=[root] ruser=[<unknown>] rhost=[192.168.1.101]
```
Going by this: [Cockpit Authentication](http://cockpit-project.org/guide/133/authentication.html) i should be able to login as root, since i can also login as root via ssh. Is this some pam config problem?

**Comment by bryteise** [comment]
Hrm could be an issue with PAM as we didn't ship one in Clear as it wasn't in the repo. I notice fedora provides one so maybe try creating /usr/share/pam.d/cockpit with the following:
`#%PAM-1.0
auth            substack     common-auth
account         required     pam_nologin.so
account         include      common-account
password        include      common-password
session         required     pam_loginuid.so
session         optional     pam_keyinit.so force revoke
session         include      password-auth
`
Which is maybe is not terrible but I'm not a pam expert. If that works for you I'll add it into our cockpit package.

**Comment by Andy2244** [comment]
I also have no real clue about pam, but now i get:
```
clear-vm cockpit-session[49967]: PAM _pam_load_conf_file: unable to open config for password-auth
clear-vm cockpit-ws[49952]: cockpit-session: couldn't open session: root: Permission denied
```

**Comment by bryteise** [comment]
Ugh sorry the last line should be:
session    include      common-session

Copypasta error (Clear's pam files have different names compared to Fedora).

**Comment by Andy2244** [comment]
np and yes this worked! 
I'm in the dashboard now, i still had to either create /etc/cockpit/ws-certs.d/ or fix the 'remotectl certificate', but i guess that's normal? No to test it on ubuntu again and see how the package behaves there.

Thx for the help and i need some time to test if everything works.

**Comment by Andy2244** [comment]
Oki did some testing and comparison with ubuntu 17.10.

1) after "sudo apt-get install cockpit" ubuntu creates `/etc/cockpit/machines.d`  and `/etc/cockpit/ws-certs.d`
The last is needed to let cockpit create a self-signed cert, otherwise you have to manually create and manage via `remotectl certificate` or certmonger.

So i think clearlinux should do the same, to allow the self-signed cert by default.

2) Without a installed https cert you need to create `/etc/cockpit/cockpit.conf`
```
[WebService]
AllowUnencrypted=true
```
or follow there [guide ](http://cockpit-project.org/blog/cockpit-158.html)to download/import the self-signed cert for your browser.

We should ensure clearlinux is able to manage https certs, do we have lets-encrypt support?

3) The diagnostic-report pane noted this, maybe we can enable this function?
`The sosreport utility is not installed.  This should not happen.  Please complain to your distribution vendor.`

4) The storage api did not work, which would be nice to get working.
`The "storaged" API is not available on this system.` 
Ubuntu had it working by using, `(udisks daemon version 2.6.5 starting)`.

5) Several machine sub-panes seem to be missing support or displayed fedora/atomic features, which should be disabled, Ubuntu did hide those panes.
Here is a comparison on what is displayed in each version:
![clearlinux](https://user-images.githubusercontent.com/5340247/34071200-f523e8a6-e272-11e7-8138-218b54fbc24d.png)
![ubuntu](https://user-images.githubusercontent.com/5340247/34071201-f53d9abc-e272-11e7-9f9b-4b89cc32885d.png)

6) There is a pam file in the git: [git](https://github.com/cockpit-project/cockpit/blob/master/tools/cockpit.pam) is your version based on it?
Here is the ubuntu 17.10 version:
```
#%PAM-1.0
auth       required     pam_sepermit.so
auth       substack     common-auth
auth       optional     pam_ssh_add.so
account    required     pam_nologin.so
account    required     pam_shells.so
account    include      common-account
password   include      common-password
# pam_selinux.so close should be the first session rule
session    required     pam_selinux.so close
session    required     pam_loginuid.so
# pam_selinux.so open should only be followed by sessions to be executed in the user context
session    required     pam_selinux.so open env_params
session    optional     pam_keyinit.so force revoke
session    optional     pam_ssh_add.so
session    include      common-session

# Read environment variables from /etc/environment and
# /etc/security/pam_env.conf.
session    required     pam_env.so # [1]
# In Debian 4.0 (etch), locale-related environment variables were moved to
# /etc/default/locale, so read that as well.
session    required     pam_env.so user_readenv=1 envfile=/etc/default/locale
```

The other features like terminal, container (docker) management did seem to work as expected, but i did not test a cluster setup or anything more complex.

thx again for the work on this!

**Comment by bryteise** [comment]
Okay, I can add systemd.tmpfiles for autocreating the /etc directories.

For lets encrypt, I think @ahkok has done all the work there and knows the best status for what things are supported. Not sure exactly what you would be needing here.

I'll take a look into the sosreport issue. Might have been an extra script somewhere.

I'll see what I can do about the panes. I hate looking at the Ubuntu repos though =P.

**Comment by ahkok** [comment]
On 12/20/2017 01:26 PM, William Douglas wrote:
> For lets encrypt, I think @ahkok has done all the work there and knows the best status for what things are supported. Not sure exactly what you would be needing here.

essentially, `certbot certonly` is supported. This is the core of 
certbot anyway and everything else sort of plug into that or make it 
less intrusive.

**Comment by bryteise** [comment]
@Andy2244 So I've tweaked some things. You should be seeing the /etc directories being created, the errors for sos and udisk not being present no longer around and hopefully a more reasonable set of items in the sub-panes.

Also I didn't comment on it before, but yes I based the idea of our pam file on the one from git.

**Comment by bryteise** [comment]
Ah this should be in release 20090 and beyond.

**Comment by Andy2244** [comment]
Thx for the work, looks better now, but still getting a lot of warnings/errors and SoS/Storage manager is not working (out of the box) ?

```
Unable to read configuration file /etc/sos.conf : No such file or directory

Failed to load config files: Failed to get contents of the config dir (/etc/libblockdev/conf.d/)Error opening directory “/etc/libblockdev/conf.d/”: No such file or directory. Using the built-in config
Can't load configuration file /etc/udisks2/udisks2.conf
polkit.service: Failed at step EXEC spawning /usr/lib/polkit-1/polkitd: No such file or directory
Failed to start Authorization Manager.

cat: /sys/kernel/kexec_crash_size: No such file or directory
```

**Comment by Andy2244** [comment]
Still getting `Unable to read configuration file /etc/sos.conf : No such file or directory` in 20250, but storage is now working, there seem to-be still some cockpit related warnings/errors in the log, but so far all the basic stuff is working.

So i guess i will close this and thanks again for the work.

**Comment by bryteise** [comment]
This can stay open as I'm tracking it, I unfortunately hit some other tasks so it isn't going to get as quick of turn around though X(. The udisks2.conf I'll take a look at, it will likely end up being similar to the sos.conf fix (and similarly the libblockdev/conf.d directory will need to get created).

The sysfs parts I am not familiar with and didn't find anything at a first look around so I'll ignore that for now at least.

The ibacm.socket is for Infiniband devices so I'm not sure why that is being started but giving an error but I'd guess is unrelated to getting cockpit working.

**Comment by bryteise** [comment]
So sos and udisks2 should have their system configuration files in place in the next release and cockpit will pull in the polkit daemon so hopefully most of those warnings are cleaned up.

I didn't add the libblockdev configuration as it wasn't required as that falls back to a built in configuration already.

**Comment by Andy2244** [comment]
oki thanks again, looks good
Now the storage page does not need a manual reload and the only errors/warnings i see now are:

```
could not read from '/sys/module/acpi_cpufreq/initstate': No such device systemd-udevd 
could not read from '/sys/module/pcc_cpufreq/initstate': No such device systemd-udevd
```
probably related to my hyper-v VM

`/usr/lib/systemd/system/ibacm.socket:15: Failed to parse address value, ignoring: rdma 4`
no clue

If i try to create a diagnostic report i get:
```
No archive has been created.

sosreport (version 3.5)
plugin haproxy does not install, skipping: No module named 'urlparse'
no valid plugins were enabled
```
Not a big problem, but seems something is still missing.

If you want you can close this issue.

**Comment by bryteise** [comment]
Yea the apci and pcc messages aren't an issue, similar for the ibacm.socket (we would want to fix that in Clear but it isn't related to cockpit).

The haproxy message confuses me a little, I'm assuming it means it isn't installed not they couldn't install it as part of running cockpit. urlparse went away in python3 though as it is now urllib.parse so probably sosreport needs to be fixed upstream is my guess. I can poke at this a little more but it will be a slow burn. Glad it is pretty usable at this point.

**Comment by Andy2244** [comment]
closing this, since so far all seems working for quite some time now.
