### ISSUE TITLE
Why use a outdated edge docker version (17.05.0-ce)?

### ISSUE THREAD

**Issue by Andy2244** [clearlinux/clr-bundles#26]
The current clearlinux docker version i get via `containers-basic` is 17.05.0-ce, which is 7 months old, but also a edge release?
Isn't the idea usually to use the stable channel for docker versions, which should be at least 17.06.02-ce or better 17.09.1-ce?
Even the edge channel is now at 17.11.0-ce, with the containerd 1.0 release.

So whats going on regarding docker and clearlinux and how can i update the docker version to a stable release?

**Comment by bryteise** [comment]
@Andy2244 we haven't really had much discussion around this yet but I'm updating to 17.09.1-ce at the moment once it passes our testing. I'm not sure we have much interest in staying on an edge version but we needed to have very recent releases historically for Clear Containers.

**Comment by Andy2244** [comment]
Stable is fine, i was just a bit surprised that clearlinux as "cloud/container" distro did not follow the stable channel closely. I found clearlinux mainly to run it on hyper-v using docker, since other "special" distros like rancheros/coreos/projectAtomic/Alpine/linuxkit/moby for one had no ready to use vdmx image and also have all there own "special" way to handle configurations.

thx for the update
