### ISSUE TITLE
Proposal - add ldap to php build

### ISSUE THREAD

**Issue by PanWieczorek** [clearlinux/clr-bundles#260]
Hi!
I noticed that `php -m` does not list ldap module, which according to https://www.php.net/manual/en/ldap.installation.php is disabled by default. Please add  --with-ldap flag to php build or provide a way to install given module

**Comment by fenrus75** [comment]
makes sense -- I made the change and it should be in the next release

**Comment by rublon-bwi** [comment]
Ldap support added in 41890
