### ISSUE TITLE
Please add plasma-systemmonitor to desktop-kde-apps

### ISSUE THREAD

**Issue by gruzgewuz** [clearlinux/clr-bundles#262]
Please add plasma-systemmonitor to one of the bundles:
desktop-kde-apps
desktop-kde

Or is there a reason why it is not included anymore?

**Comment by fenrus75** [comment]
added to desktop-kde

not sure why it was not there (anymore) -- perhaps it got implicitly pulled
in before but that stopped . explicit is better anyway

It'll be in the next release
