### ISSUE TITLE
add zerofree into the admin/disk-utils bundle

### ISSUE THREAD

**Issue by Andy2244** [clearlinux/clr-bundles#29]
I miss the zerofree tool, so i can easily compact the dynamic vhdx disks. While this can also be done via cat /dev/zero > /var/tmp/zero.out, its not quite save to-do if some unaware/bad services also run simultaneously.

So just throw it into the admin/disk-util bundles.

thx Andy

**Comment by bryteise** [comment]
zerofree's upstream seems to no longer be online and does not appear to be maintained. I can grab the source tar from another distro but this will definitely get my cross looks from the security folks.

**Comment by Andy2244** [comment]
Its the tool, mainly mentioned if you google for "compact linux vhdx", but any tool that does the same will work too. Maybe there is a more current tool or it was merged with some general disk util package? All it does is zeroout the empty space, without generating a "disk full" event.
