### ISSUE TITLE
Please provide bundles which can contain these packages for clear-xx-installer.img

### ISSUE THREAD

**Issue by zyuan2x** [clearlinux/clr-bundles#30]
I need blow packages with bundles to install on Clear Linux. These packages block my testing now. 
Do you have any ideas about install above packages on Clear Linux OS without bundles?
Thanks for Clear Linux Team!

**== package list ==**
ucf
bundler
udhcpc 
avrdude 
i2cdetect 
i2cget 
memtester 
glxgears 
startx 
pgrep 
shuf
acpi-support
pm-utils
busybox
busybox-static
iputils-ping
libpython2.7
linux-tools-common
acpica-tools
pcregrep
mesa-utils
libx32gcc-4.8-dev 
libc6-dev-i386
nfs-kernel-server
i2c-tools

**Comment by zyuan2x** [comment]
I install above packages with manually.

**Comment by bryteise** [comment]
Do you feel like we should try and add these packages into bundles where they would make sense? I know a few of these might not be added or might exist already as far as functionality goes though.

**Comment by Syzygies** [comment]
While I've accepted the philosophy that I'll be doing manual installs, I'm reading each of these issues in hopes of reading a comment somewhere that leads me to a guide on writing my own bundles, together with a description of the issues that worry everyone about conflicting package managers and such. I don't like to do anything by hand that I can script...

So I don't want you to "try and add these packages into bundles" I want you to teach us to do it.

Despite the stated "Cloud and IoT" mission, Clear Linux is beating out other Linuxes handily on bare metal in computational benchmarks. I'm a mathematician building compute servers for personal use, and in 2018 Clear Linux is the obvious choice for this. The first place where this philosophy difference creates friction is hardware monitoring; in my builds the engine is always too big for the car, and needs to be tamed for 24/7 torture-test level workloads.

**Comment by bryteise** [comment]
@Syzygies So there is work underway to enable more minimal bundles and after that there is also a design to be started on enabling 3rd party packages via alternate repositories. Currently if you want to maintain your own bundles, using [mixer](https://github.com/clearlinux/mixer-tools) is the only way to handle it. The documentation is unfortunately behind as the enabling work for the features I talked about before are causing a large amount of churn in the code base. Perhaps @tmarcu or @matthewrsj would know better where an up to date getting started with mixer exists though.

**Comment by bryteise** [comment]
Pundles and devpkg bundles have been released so I'm closing this issue as the mechanism for resolving the main issue has been created.
