### ISSUE TITLE
Out of memory error with filedescriptor leak when installing bundle: sysadmin-basic

### ISSUE THREAD

**Issue by FireballDWF** [clearlinux/clr-bundles#31]
$ docker run -it clearlinux:latest bash
root@2c56d3bbcfb7 / # cd /home
root@2c56d3bbcfb7 /home # swupd bundle-add sysadmin-basic
swupd-client bundle adder 3.13.1
   Copyright (C) 2012-2017 Intel Corporation

Downloading packs...

Extracting sysadmin-basic pack for version 19150
	...100%
Installing bundle(s) files...
	...100%
Calling post-update helper scripts.
[ERROR] cbm (../src/lib/files.c:L165): Invalid block device: /
[ERROR] cbm (../src/lib/system_stub.c:L31): Invalid block device: 0:66
Out of memory[ERROR] cbm (../src/bootman/update.c:L250): No kernels discovered in ///usr/lib/kernel, bailing
Possible filedescriptor leak : 7 (socket:[10206615])
Bundle(s) installation done.
root@2c56d3bbcfb7 /home #

**Comment by ImreSamu** [comment]
Hi @FireballDWF ,
Can you force a manual update:  `swupd update` ?
As I see after the updating 
*  "Latest server version: 20060"  ( not 19150)
*  "swupd-client bundle adder 3.14.2"  ( not 3.13.1)

**Comment by FireballDWF** [comment]
Another way to reproduce failure:
$ docker run -it clearlinux:latest bash
root@eb1270e35241 / # swupd bundle-add os-core-update-dev
swupd-client bundle adder 3.13.1
   Copyright (C) 2012-2017 Intel Corporation

Downloading packs...

Extracting os-core-update-dev pack for version 19150
	...16%
Extracting os-core-dev pack for version 19150
	...33%
Extracting dev-utils pack for version 19150
	...50%
Extracting python-basic pack for version 19060
	...66%
Extracting python3-basic pack for version 19060
	...83%
Extracting perl-basic pack for version 19010
	...100%
Installing bundle(s) files...
	...100%
Calling post-update helper scripts.
[ERROR] cbm (../src/lib/files.c:L165): Invalid block device: /
[ERROR] cbm (../src/lib/system_stub.c:L31): Invalid block device: 0:86
Out of memory[ERROR] cbm (../src/bootman/kernel.c:L247): Error opening ///usr/lib/kernel: No such file or directory
[ERROR] cbm (../src/bootman/update.c:L250): No kernels discovered in ///usr/lib/kernel, bailing
Possible filedescriptor leak : 7 (socket:[12202491])
Bundle(s) installation done.
root@eb1270e35241 / #

**Comment by FireballDWF** [comment]
Did not solve the problem:
 $ docker run -it clearlinux:latest bash
root@6b2e2e15585e / #  cd /home
root@6b2e2e15585e /home # swupd update
swupd-client software update 3.13.1
   Copyright (C) 2012-2017 Intel Corporation

Update started.
Attempting to download version string to memory
Preparing to update from 19150 to 19450
Downloading packs...
	...100%

Statistics for going from version 19150 to version 19450:

    changed bundles   : 2
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 103
    new files         : 336
    deleted files     : 4

Starting download of remaining update content. This may take a while...

File /usr/bin/bridge was not in a pack
	...100%
Finishing download of update content...
Staging file content
Applying update
	...100%
Update was applied.
Calling post-update helper scripts.
Update took 11.6 seconds
Update successful. System updated from version 19150 to version 19450
379 files were not in a pack
swupd-client software update 3.14.1
   Copyright (C) 2012-2017 Intel Corporation

Update started.
Attempting to download version string to memory
Preparing to update from 19460 to 20060
Downloading packs...

Extracting os-core pack for version 20060
	...50%
Extracting os-core-update pack for version 20060
	...100%

Statistics for going from version 19460 to version 20060:

    changed bundles   : 2
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 297
    new files         : 8
    deleted files     : 5

Starting download of remaining update content. This may take a while...
	...100%
Finishing download of update content...
Staging file content
Applying update
	...100%
Update was applied.
Calling post-update helper scripts.
Update took 2.5 seconds
Update successful. System updated from version 19460 to version 20060
root@6b2e2e15585e /home # swupd bundle-add os-clr-on-clr desktop-dev database-basic-dev
swupd-client bundle adder 3.14.2
   Copyright (C) 2012-2017 Intel Corporation

Downloading packs...

Extracting os-clr-on-clr pack for version 20060
	...2%
Extracting storage-utils-dev pack for version 20060
	...5%
Extracting storage-utils pack for version 20060
	...8%
Extracting os-core-update-dev pack for version 20060
	...11%
Extracting openssh-server pack for version 20060
	...13%
Extracting network-basic-dev pack for version 20060
	...16%
Extracting network-basic pack for version 20060
	...19%
Extracting mixer pack for version 20000
	...22%
Extracting os-installer pack for version 20060
	...25%
Extracting mail-utils-dev pack for version 20060
	...27%
Extracting mail-utils pack for version 20060
	...30%
Extracting kvm-host pack for version 20060
	...33%
Extracting koji pack for version 20060
	...36%
Extracting web-server-basic pack for version 20060
	...38%
Extracting go-basic pack for version 20060
	...41%
Extracting editors pack for version 20060
	...44%
Extracting dev-utils-dev pack for version 20060
	...47%
Extracting python-basic-dev pack for version 20060
	...50%
Extracting perl-basic-dev pack for version 20060
	...52%
Extracting c-basic pack for version 20060
	...55%
Extracting desktop-dev pack for version 20060
	...58%
Extracting sysadmin-basic-dev pack for version 20060
	...61%
Extracting desktop pack for version 20060
	...63%
Extracting sysadmin-basic pack for version 20060
	...66%
Extracting desktop-locales pack for version 19800
	...69%
Extracting desktop-assets pack for version 19460
	...72%
Extracting desktop-apps pack for version 20060
	...75%
Extracting desktop-gnomelibs pack for version 20060
	...77%
Extracting libX11client pack for version 20060
	...80%
Extracting database-basic-dev pack for version 20060
	...83%
Extracting os-core-dev pack for version 20060
	...86%
Extracting dev-utils pack for version 20060
	...88%
Extracting python-basic pack for version 19460
	...91%
Extracting python3-basic pack for version 20060
	...94%
Extracting perl-basic pack for version 20060
	...97%
Extracting database-basic pack for version 20060
	...100%
Installing bundle(s) files...
	...100%
Calling post-update helper scripts.
[ERROR] cbm (../src/lib/files.c:L165): Invalid block device: /
[ERROR] cbm (../src/lib/system_stub.c:L31): Invalid block device: 0:67
Out of memory[ERROR] cbm (../src/bootman/update.c:L250): No kernels discovered in ///usr/lib/kernel, bailing
Possible filedescriptor leak : 7 (socket:[12905714])
Bundle(s) installation done.
root@6b2e2e15585e /home #

**Comment by FireballDWF** [comment]
Following shows how to reproduce with only a single bundle:
$ docker run -it clearlinux:latest bash
root@fd4707d7a728 / # cd home
root@fd4707d7a728 /home # swupd update
swupd-client software update 3.13.1
   Copyright (C) 2012-2017 Intel Corporation

Update started.
Attempting to download version string to memory
Preparing to update from 19150 to 19450
Downloading packs...
	...100%

Statistics for going from version 19150 to version 19450:

    changed bundles   : 2
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 103
    new files         : 336
    deleted files     : 4

Starting download of remaining update content. This may take a while...

File /usr/bin/bridge was not in a pack
	...100%
Finishing download of update content...
Staging file content
Applying update
	...100%
Update was applied.
Calling post-update helper scripts.
Update took 20.2 seconds
Update successful. System updated from version 19150 to version 19450
379 files were not in a pack
swupd-client software update 3.14.1
   Copyright (C) 2012-2017 Intel Corporation

Update started.
Attempting to download version string to memory
Preparing to update from 19460 to 20060
Downloading packs...

Extracting os-core pack for version 20060
	...50%
Extracting os-core-update pack for version 20060
	...100%

Statistics for going from version 19460 to version 20060:

    changed bundles   : 2
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 297
    new files         : 8
    deleted files     : 5

Starting download of remaining update content. This may take a while...
	...100%
Finishing download of update content...
Staging file content
Applying update
	...100%
Update was applied.
Calling post-update helper scripts.
Update took 4.0 seconds
Update successful. System updated from version 19460 to version 20060
root@fd4707d7a728 /home # swupd bundle-add sysadmin-basic
swupd-client bundle adder 3.14.2
   Copyright (C) 2012-2017 Intel Corporation

Downloading packs...

Extracting sysadmin-basic pack for version 20060
	...100%
Installing bundle(s) files...
	...100%
Calling post-update helper scripts.
[ERROR] cbm (../src/lib/files.c:L165): Invalid block device: /
[ERROR] cbm (../src/lib/system_stub.c:L31): Invalid block device: 0:40
Out of memory[ERROR] cbm (../src/bootman/update.c:L250): No kernels discovered in ///usr/lib/kernel, bailing
Possible filedescriptor leak : 6 (socket:[14004480])
Possible filedescriptor leak : 7 (socket:[14004487])
Bundle(s) installation done.
root@fd4707d7a728 /home #

**Comment by bryteise** [comment]
These are all run in a docker container if I'm reading this correctly. In that case the error you are seeing isn't a problem but the cbm error is odd since it shouldn't be run at all.

**Comment by FireballDWF** [comment]
Correct, running ClearLinux within docker.  I'm not seeing any impact other than the error message, but it's appearance seemed worth reporting so can be made more graceful.

**Comment by bryteise** [comment]
@FireballDWF Ah this is actually just a flag issue. When swupd is run in docker you want to pass -b to swupd's subcommands to avoid calling cbm as there isn't any reason for it to run.

**Comment by FireballDWF** [comment]
1. The "-b" option is not documented in the man page nor "swupd -h", please update
2  It would be more graceful for the swupd program to not invoke cbm when running within a container.  Should not be hard to detect this condition.

**Comment by bryteise** [comment]
It is under swupd's subcommand help, so swupd update -h would show it for example. The man pages are definitely out of date though and need to be updated.

While swupd does do validation on when certain things that are updated need to trigger cbm to run, there isn't any detection on if swupd is run in a container or not. I think the team determined that wasn't particularly simple to do and introduced the flag as a work around. I am poking @matthewrsj for this as it is a swupd issue.

**Comment by matthewrsj** [comment]
@bryteise is correct, `-b` was added as a workaround to running in a container. Running in docker *can* be detected pretty easily by checking for the existence of `/.dockerenv` or checking for lines containing `/docker/` in `/proc/1/cgroup`. Opened https://github.com/clearlinux/swupd-client/issues/359 to discuss.

The man page being out of date is definitely an issue. Opened https://github.com/clearlinux/swupd-client/issues/358.

**Comment by bryteise** [comment]
Closing this as the new issues to address this problem have been opened in the swupd-client repo.
