### ISSUE TITLE
swupd update: Possible filedescriptor leak

### ISSUE THREAD

**Issue by FireballDWF** [clearlinux/clr-bundles#34]
How to Reproduce:
1. Launch ami-9d38e5e7 on AWS EC2.
2. ssh to instance launched in step 1.
3. Run "sudo swupd update" and observe the subject warning reported twice, as can be seen below:

clear@clr-43b103bed13e4c4a91cf319e110ade97 ~ $ sudo swupd update
swupd-client software update 3.13.0
   Copyright (C) 2012-2017 Intel Corporation

Update started.
Attempting to download version string to memory
Preparing to update from 18940 to 19450
Downloading packs...

Extracting bootloader pack for version 19100
	...16%
Extracting kernel-aws pack for version 19270
	...33%
Extracting openssh-server pack for version 19190
	...50%
Extracting os-cloudguest-aws pack for version 19060
	...66%
Extracting os-core pack for version 19450
	...83%
Extracting os-core-update pack for version 19450
	...100%

Statistics for going from version 18940 to version 19450:

    changed bundles   : 6
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 293
    new files         : 906
    deleted files     : 6

Starting download of remaining update content. This may take a while...
	...100%
Finishing download of update content...
Staging file content
Applying update
	...100%
Update was applied.
Calling post-update helper scripts.
Possible filedescriptor leak : 6 (socket:[13344])
Possible filedescriptor leak : 7 (socket:[13348])
Update took 11.9 seconds
Update successful. System updated from version 18940 to version 19450
swupd-client software update 3.14.1
   Copyright (C) 2012-2017 Intel Corporation

Update started.
Attempting to download version string to memory
Preparing to update from 19460 to 20260
Downloading packs...

Extracting bootloader pack for version 20230
	...16%
Extracting kernel-aws pack for version 20220
	...33%
Extracting openssh-server pack for version 20230
	...50%
Extracting os-cloudguest-aws pack for version 20260
	...66%
Extracting os-core pack for version 20260
	...83%
Extracting os-core-update pack for version 20260
	...100%

Statistics for going from version 19460 to version 20260:

    changed bundles   : 6
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 392
    new files         : 615
    deleted files     : 23

Starting download of remaining update content. This may take a while...
	...100%
Finishing download of update content...
Staging file content
Applying update
	...100%
Update was applied.
Calling post-update helper scripts.
Possible filedescriptor leak : 6 (socket:[15609])
Possible filedescriptor leak : 7 (socket:[15612])
Update took 11.4 seconds
Update successful. System updated from version 19460 to version 20260
clear@clr-43b103bed13e4c4a91cf319e110ade97 ~ $

**Comment by phmccarty** [comment]
Perhaps a duplicate of https://github.com/clearlinux/swupd-client/issues/347 ?

**Comment by FireballDWF** [comment]
Closed as Dup, I've now subscribed to the above
