### ISSUE TITLE
cloud-control bundle missing dependancy for awscli: colorama

### ISSUE THREAD

**Issue by FireballDWF** [clearlinux/clr-bundles#35]
# Actual Result:
$ aws --version
Traceback (most recent call last):
  File "/usr/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/lib/python3.6/site-packages/awscli/clidriver.py", line 28, in <module>
    from awscli.formatter import get_formatter
  File "/usr/lib/python3.6/site-packages/awscli/formatter.py", line 20, in <module>
    from awscli.table import MultiTable, Styler, ColorizedStyler
  File "/usr/lib/python3.6/site-packages/awscli/table.py", line 17, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'
clear@clr-3d5ff99de3894b32abaae7756bfa51ef ~ $ 

# How to reproduce:
1. Launch ami-9d38e5e7 on AWS EC2.
2. ssh to instance launched in step 1.
3. sudo swupd update
4. sudo swupd bundle-add cloud-control
5. aws --version

# Example of steps 3-5:
$ sudo swupd update
swupd-client software update 3.13.0
   Copyright (C) 2012-2017 Intel Corporation

Update started.
Attempting to download version string to memory
Preparing to update from 18940 to 19450
Downloading packs...

Extracting bootloader pack for version 19100
	...16%
Extracting kernel-aws pack for version 19270
	...33%
Extracting openssh-server pack for version 19190
	...50%
Extracting os-cloudguest-aws pack for version 19060
	...66%
Extracting os-core pack for version 19450
	...83%
Extracting os-core-update pack for version 19450
	...100%

Statistics for going from version 18940 to version 19450:

    changed bundles   : 6
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 293
    new files         : 906
    deleted files     : 6

Starting download of remaining update content. This may take a while...
	...100%
Finishing download of update content...
Staging file content
Applying update
	...100%
Update was applied.
Calling post-update helper scripts.
Possible filedescriptor leak : 6 (socket:[13882])
Possible filedescriptor leak : 7 (socket:[13886])
Update took 39.5 seconds
Update successful. System updated from version 18940 to version 19450
swupd-client software update 3.14.1
   Copyright (C) 2012-2017 Intel Corporation

Update started.
Attempting to download version string to memory
Preparing to update from 19460 to 20260
Downloading packs...

Extracting bootloader pack for version 20230
	...16%
Extracting kernel-aws pack for version 20220
	...33%
Extracting openssh-server pack for version 20230
	...50%
Extracting os-cloudguest-aws pack for version 20260
	...66%
Extracting os-core pack for version 20260
	...83%
Extracting os-core-update pack for version 20260
	...100%

Statistics for going from version 19460 to version 20260:

    changed bundles   : 6
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 392
    new files         : 615
    deleted files     : 23

Starting download of remaining update content. This may take a while...
	...100%
Finishing download of update content...
Staging file content
Applying update
	...100%
Update was applied.
Calling post-update helper scripts.
Possible filedescriptor leak : 6 (socket:[16146])
Possible filedescriptor leak : 7 (socket:[16149])
Update took 3.8 seconds
Update successful. System updated from version 19460 to version 20260
clear@clr-3d5ff99de3894b32abaae7756bfa51ef ~ $ aws
-bash: aws: command not found
clear@clr-3d5ff99de3894b32abaae7756bfa51ef ~ $ sudo swupd bundle-add cloud-control
swupd-client bundle adder 3.14.3
   Copyright (C) 2012-2017 Intel Corporation

Downloading packs...

Extracting cloud-control pack for version 20260
	...14%
Extracting python-basic pack for version 19460
	...28%
Extracting network-basic pack for version 20260
	...42%
Extracting python3-basic pack for version 20260
	...57%
Extracting perl-basic pack for version 20230
	...71%
Extracting kvm-host pack for version 20220
	...85%
Extracting libX11client pack for version 20260
	...100%
Installing bundle(s) files...
	...100%
Calling post-update helper scripts.
Bundle(s) installation done.
clear@clr-3d5ff99de3894b32abaae7756bfa51ef ~ $ aws --version
Traceback (most recent call last):
  File "/usr/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/lib/python3.6/site-packages/awscli/clidriver.py", line 28, in <module>
    from awscli.formatter import get_formatter
  File "/usr/lib/python3.6/site-packages/awscli/formatter.py", line 20, in <module>
    from awscli.table import MultiTable, Styler, ColorizedStyler
  File "/usr/lib/python3.6/site-packages/awscli/table.py", line 17, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'

**Comment by bryteise** [comment]
Ah well that should be an easy fix, thanks for spotting this!

**Comment by bryteise** [comment]
Should be resolved in the afternoon release.

**Comment by FireballDWF** [comment]
verified resolved
