### ISSUE TITLE
libvsqlitepp-dev and libgdal-dev needed

### ISSUE THREAD

**Issue by FireballDWF** [clearlinux/clr-bundles#37]
The equivalent of Debian packages libvsqlitepp-dev libgdal-dev are needed for building MySql Workbench.  Was not able to find them with variations of the following searches:
swupd search libgdal
swupd search libvsqlitepp

**Comment by bryteise** [comment]
So we don't have either of those libraries at the moment, I'll take a look at adding them.

**Comment by bryteise** [comment]
Change proposed in https://lists.clearlinux.org/pipermail/dev/2018-January/001230.html

**Comment by bryteise** [comment]
These should be in the next release in database-basic.

**Comment by bryteise** [comment]
These have been released, @FireballDWF is are you still running into issues building MySql Workbench?
