### ISSUE TITLE
R does not draw the font properly when writing a plot as PNG.

### ISSUE THREAD

**Issue by ghuls** [clearlinux/clr-bundles#38]
Installed packages:
```
swupd bundle-add \
        editors \
        database-basic-dev \
        dev-utils \
        java-basic \
        python-basic \
        python-basic-dev \
        python-extras \
        R-basic \
        R-extras \
        shells \
        sysadmin-basic
```

Make a basic plot in R:
```
> png('test.png')
> plot(2,3)
> dev.off()
pdf 
  2 
> pdf('test.pdf')
> plot(2,3)
> dev.off()
pdf 
  2 
```

The PNG version does not contain any font (problem with cairo?).
The PDF version looks OK.

![test](https://user-images.githubusercontent.com/1299177/34950173-aff52fbc-fa12-11e7-9d80-67a9de065d2c.png)
[test.pdf](https://github.com/clearlinux/clr-bundles/files/1632169/test.pdf)

Is there another package that I should install to fix this or is it a bug?

**Comment by bryteise** [comment]
Looks like a bug to me, the bundle should be self contained enough to display correctly. @mrkz Would you be able to look at this?

**Comment by ghuls** [comment]
@mrkz fca179da30e17a5f528b4c946ba016736b97a67a seems to work (when I install the packages manually).

Is there a better way to install certain packages?
The following looks ugly:
```
curl -O https://download.clearlinux.org/current/x86_64/os/Packages/clear-font-1-11.x86_64.rpm
curl -O https://download.clearlinux.org/current/x86_64/os/Packages/clear-font-data-1-11.x86_64.rpm

rpm -ivh --nodeps clear-font-1-11.x86_64.rpm
rpm -ivh --nodeps clear-font-data-1-11.x86_64.rpm
```

**Comment by mrkz** [comment]
@ghuls The fix landed for CLR version >= 20470.

Thanks for your bug report!.

If you find anything odd as you continue using clearlinux, please do open a bug here, send us a mail to our [mailing list](https://lists.clearlinux.org/mailman/listinfo/dev) or feel free to ping us at #clearlinux @ freenode :)

**Comment by mrkz** [comment]
aditionally, if you want to remove all locally installed RPM you can do so by running
```
# swupd verify --fix
```
and you may also remove the RPM database (so it doesn't bother you later on)
```
# rm -rf /var/lib/rpm
```
