### ISSUE TITLE
Add Wireshark for network troubleshooting

### ISSUE THREAD

**Issue by FireballDWF** [clearlinux/clr-bundles#39]
Source at https://github.com/wireshark/wireshark

Tool is useful for troubleshooting performance issues involving network traffic

**Comment by bwarden** [comment]
There is now a wireshark bundle.

**Comment by probonopd** [comment]
As another option, there is an [inofficial Wireshark](https://bintray.com/probono/AppImages/Wireshark/_latestVersion#files) [AppImage](https://appimage.org/) that also runs fine on Clear Linux OS:

![wireshark](https://user-images.githubusercontent.com/2480569/48312372-69ab5200-e5a5-11e8-807c-89c174ed4358.png)

As of now, you need to [enable FUSE](https://github.com/clearlinux/distribution/issues/273) first.
