### ISSUE TITLE
Please provide a Live ISO

### ISSUE THREAD

**Issue by probonopd** [clearlinux/clr-bundles#4]
Please provide a [Live ISO](https://livecdlist.com/) which would allow one to boot Clear Linux on real hardware without having to install it, and without having to use a VM.

**Comment by sofar** [comment]
There is a live image already:

https://download.clearlinux.org/image/clear-13010-live.img.xz

We do not provide ISO images since we do not support iso9660 bootable CD's. These images are raw disk images and require UEFI to boot.

**Comment by probonopd** [comment]
Thanks @sofar, can you give an example how to configure a GRUB 2 bootloader to boot this file?

**Comment by bryteise** [comment]
@probonopd Sorry this dropped off what I was thinking about completely, we don't really use grub2 directly for the project but the image is intended to be bootable via the bios but it shouldn't be a problem to chain load similar to how you would any other UEFI image.

**Comment by probonopd** [comment]
Thanks @bryteise it'd be awesome if you could give an example of how to do this using GRUB2. GRUB2 can loop-mount filesystem images and start the kernel from there, but the system that is being booted also needs to understand how to loop-mount an image in order to continue booting. Most systems (e.g., Ubuntu) have a command line option that is understood by the initrd for this purpose. How would that work with Clearlinux?

For example, the following works because Ubuntu understands `iso-scan/filename=${iso_path}`:

```
menuentry "ubuntu-gnome-17.04-beta2-desktop-amd64.iso - casper 1.380" --class ubuntu {
        iso_path="/boot/iso/ubuntu-gnome-17.04-beta2-desktop-amd64.iso"
        search --no-floppy --file ${iso_path} --set
        live_args="for-casper --> iso-scan/filename=${iso_path} console-setup/layoutcode=de locale= timezone=Europe/Berlin username=me hostname=host noprompt init=/isodevice/boot/customize/init max_loop=256"
        custom_args=""
        iso_args=" "
        loopback loop ${iso_path}
        linux (loop)/casper/vmlinuz.efi file=/cdrom/preseed/ubuntu-gnome.seed boot=casper iso-scan/filename=${iso_path} quiet splash --- ${live_args} ${custom_args} ${iso_args}
        initrd (loop)/casper/initrd.lz /boot/iso/additional-initramfs/initramfs
}
```

**Comment by bryteise** [comment]
@probonopd oh that is interesting, I have not really used grub2 myself so I didn't even know that was a feature. Perhaps @ikeydoherty would have some insight from his experiences.

**Comment by ikeydoherty** [comment]
Yeah I mean if you're trying to do loopback mounts you basically need an initrd. For our world that effectively means using `dracut` and `dmsquash-live`

**Comment by probonopd** [comment]
>  if you're trying to do loopback mounts you basically need an initrd. For our world that effectively means using dracut and dmsquash-live

Yes, how would we do that?

**Comment by bryteise** [comment]
@probonopd Looking at this again. While we have added dracut to the distro and it is something you could create yourself, I don't image that there will be an image created by us that would provide this functionality any time soon. I'll throw this over to @alexjch and see if he is interested in making such an initrd and liveiso style image.

**Comment by probonopd** [comment]
It'd certainly help tremendously to have a downloadable Live ISO, especially for quickly evaluating your distribution on real hardware. Plus it is so commonplace for distributions to have Live ISOs that it can almost be expected these days. Who wants to install a full system just to do a quick evaluation? 

Thanks for your consideration @bryteise and @alexjch.

**Comment by sofar** [comment]
We have live images, already. This does not require an ISO. The live image hosted on https://download.clearlinux.org/image/ do not require installation. But they do require UEFI.

**Comment by probonopd** [comment]
Excellent @sofar, so making an ISO shouldn't be so much extra work, right? It would allow the images to be integrated into systems like [SystemImageKit](https://github.com/probonopd/SystemImageKit) that can boot a multitude of Live ISOs for almost all distributions which can be extremely handy for testing...

![](https://user-images.githubusercontent.com/2480569/32960053-e1b345d4-cbc3-11e7-9f34-c1cc11b5b1c7.png)

**Comment by sofar** [comment]
> so making an ISO shouldn't be so much extra work, right?

this is a misconception. It's also outside scope and there are no resources to do this work. "maybe later".

**Comment by alexjch** [comment]
Sorry for missing this thread. I've been working on and off in the creation of an ISO for our internal use (no grub, no dracut). 

I have an ISO working, but I have not tested it with real hardware only VM's the ISO will be available for tomorrow's build (12/22/2017) under ```current/clear-<release #>-installer.iso.xz ```. This is still WIP that's the reason this file is not under ```image``` directory where the official images can be found.

There's already a ```clear-<release #>-installer.iso.xz``` don't use that image.  I'm almost certain that it will not work for real hardware (only VM's)

**Comment by probonopd** [comment]
Hello @alexjch thanks for pointing me to `installer.iso.xz`. However I am looking for a Live ISO that can run _without_ the need for installation. Like an Ubuntu Live ISO.

**Comment by alexjch** [comment]
@probonopd: the changes that I mentioned on my previous post were done to eventually have multiple images to boot into not only an installer. Maybe in the future we will have a Live image ,but for now (as mentioned by @sofar) this is outside scope.

**Comment by ahkok** [comment]
We're making installer ISO images, but live ISO images are not going to be made. Please use KVM in UEFI mode to run live images instead, or use the ISO installer to create a non-UEFI install instead in your VM if you really can't find a VM hypervisor that supports UEFI.

**Comment by probonopd** [comment]
Well, the point is that I don't want to use a VM but bare metal...

**Comment by sofar** [comment]
You can just alt-f2 on the installer image to get a shell....

**Comment by sofar** [comment]
besides that, what kind of bare metal doesn't support UEFI *and* runs clearlinux (which requires sse4_1)?

**Comment by probonopd** [comment]
Well, I was hoping for the equivalent of a Ubuntu Live ISO that just runs about everywhere.

**Comment by sofar** [comment]
At this point, all I can do is point to github.com/clearlinux/ister, with the polite request to send patches. We don't have the bandwidth to make more images, as each image we produce requires constant QA time, twice daily. This is simply just out of our time budget.

**Comment by probonopd** [comment]
Thanks @sofar. Wasn't aware of ister, will check it out.
