### ISSUE TITLE
kernel-aws needs ENA - Elastic Network Adapter

### ISSUE THREAD

**Issue by FireballDWF** [clearlinux/clr-bundles#40]
The kernel in kernel-aws needs to be updated to include https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html#enhanced-networking-ena-linux then replace 
https://aws.amazon.com/marketplace/pp/B075TXF7KJ with an AMI which includes the ENA enanabled kernel-aws.  This is required in order to be able to launch on C5 and M5 instance types.

**Comment by mrkz** [comment]
@miguelinux ^

**Comment by FireballDWF** [comment]
Moved to https://github.com/clearlinux/distribution/issues/65
