### ISSUE TITLE
hyper-v "time synchronization" integration not working in hyper-v image?

### ISSUE THREAD

**Issue by Andy2244** [clearlinux/clr-bundles#44]
I noticed that even if i enable "time synchronization" in the hyper-v integration host options, after i wake my VM host from a sleep state, the date/time is not updated and the VM is frozen from where the host was put into sleep mode. At some point the network time synchronization kicks in, but this often takes to long and leaves the system in a "Bad" date state. So i have to manually restart the network-time service.

As i understand it the "time synchronization" integration feature should take care of this even without network-time. So it seems the hyper-v image is not correctly using or has support for this feature?

**Comment by bryteise** [comment]
Mind moving this issue over [here](https://github.com/clearlinux/distribution) as that is where we are trying to funnel new issues for the distro.

**Comment by Andy2244** [comment]
sure!
