### ISSUE TITLE
update boto package from 1.7.4 to 1.7.21

### ISSUE THREAD

**Issue by FireballDWF** [clearlinux/clr-bundles#46]
Current boto3 package uses 1.7.4 from x while 1.7.21 is currently latest release.  Need at least 1.7.10.  pip install --user is an acceptable workaround until package in bundle upgraded.

**Comment by bryteise** [comment]
@FireballDWF We've moved our issue reporting to https://github.com/clearlinux/distribution/ if you don't mind filing this there, thanks!
