### ISSUE TITLE
Please provide a mechanism so that users can cherry pick only a subset of packages within a bundle.

### ISSUE THREAD

**Issue by ashahba** [clearlinux/clr-bundles#5]
Currently we are in the process of converting our base docker images to pull from clear-linux.
There are certain packages we want them to be present in the docker like vim(or even vim-tiny). 
If I use bundles then the lightest one seems to be "editors" bundle, but that bring several other editors that I don't need.
For example to get the required packages for my docker image, I have added this RUN command at the beginning: (Please see here: https://github.com/tapanalyticstoolkit/spark-tk-jupyter/blob/master/Dockerfile)

**_# Install required bundles
RUN swupd bundle-add \\
    editors \\
    java-basic \\
    python-basic \\
    python-basic-dev\ \
    python-extras \\
    machine-learning-basic_** 

but this one single command add 3.9 GB disk space to my docker image.
The final image is 5.2 GB but if I use debian:jessie as the base my image is only 2 GB.

**Comment by bryteise** [comment]
This is really great feedback for us, thanks! There might be some things you can do to avoid needing all of these bundles but I'm not sure how much it will change your image size.

Depending on what you need to do machine-learning-basic installs many python components used for that workload so you might only need java-basic, machine-learning-basic and editors (if you need to build python modules in c, python-basic-dev is going to be needed too).

As far as being able to select subsets of bundles, that is a feature we haven't had time to look at yet but based on user feedback is becoming a higher priority.

If you need to get the absolute smallest docker image there are other options (using [mixer](https://clearlinux.org/documentation/mixer.html)) but that adds more process to image creation.

**Comment by sofar** [comment]
To better decide whether we can tailor bundles, it would really help if you could list the full requirements.

The editors pack is only 59mb(compressed, sure). It doesn't exactly explain the 3.2GB data size discrepancy, so your issue seems to be with some of the other components.

java-basic and machine-learning-basic are the two largest bundles we ship - maybe we can split them out if we could determine what is optional for the task at hand...

**Comment by bryteise** [comment]
@ashahba So we have made adjustments to a number of these bundles in order to improve their space usage. Hopefully you have seen some improvements now.

**Comment by ashahba** [comment]
Thanks @bryteise for the update. I'll try updating the image for our next build and I'll keep you posted.
