### ISSUE TITLE
in desktop bundle on 29th June, network-manager-applet caused gnome-shell crash

### ISSUE THREAD

**Issue by kcome** [clearlinux/clr-bundles#52]
The newly updated network-manager-applet in 23370 caused gnome-shell unable to start. 

found in 'journalctl -b', the modemManager.js from gnome-shell couldn't find NMA:
"Typelib file for namespace 'NMA' (any version) not found". 

My temporary solution is compiling and installing the previous version of network-manager-applet, and it works.

Might be a helpful discussion in ubuntu https://ubuntuforums.org/archive/index.php/t-2385745.html

**Comment by kcome** [comment]
@mrkz @bryteise thanks for looking into this issue.

**Comment by FoxBuru** [comment]
Can confirm this problem too. Copying manually the files NMA-1.0.typelib and NMGtk-1.0.typelib into /usr/lib64/girepository-1.0 should make it work correctly. In my case, I could acknowledge this error once I did a reboot (with the subsequent gdm fault because this typelib not being found).

**Comment by mrkz** [comment]
This is a duplicate of https://github.com/clearlinux/distribution/issues/111 which is fixed.

**Comment by kcome** [comment]
Thank all for helping
