### ISSUE TITLE
Add udhcpc in network-basic bundle

### ISSUE THREAD

**Issue by zyuan2x** [clearlinux/clr-bundles#55]
We need udhcpc in network-basic bundle to support some network automation test.

**Comment by bryteise** [comment]
Is there a reason systemd is unable to it's dhcp client for this testing?

**Comment by zyuan2x** [comment]
which systemd bundle can provide this function?

**Comment by bryteise** [comment]
os-core, see https://www.freedesktop.org/software/systemd/man/systemd.network.html

**Comment by zyuan2x** [comment]
@bryteise  Thanks! Let me try it.
