### ISSUE TITLE
Add libvirt-dev to kvm-host bundle

### ISSUE THREAD

**Issue by bswinnerton** [clearlinux/clr-bundles#61]
👋 Hi there!

I'm using the kvm-host bundle, and it's working great. I run a Grafana instance and I'd like to get some libvirt related data out of it. I started researching and there's a tool to pull data out using Prometheus over in https://github.com/kumina/libvirt_exporter, but it depends on libvirt-dev in order to access the libvirt APIs and get metrics.

It [looks like](https://github.com/clearlinux/clr-bundles/blob/2de846c233586e3c038b79084aa7ae958bf57f96/bundles/os-utils-gui-dev#L392) the libvirt-dev package is available in `os-utils-gui-dev`, but I was wondering if it could be added to the `kvm-host` bundle, or perhaps adding a `kvm-host-dev` bundle with it 🙏.

##

For posterity, when trying to build the [libvirt_exporter source](https://github.com/kumina/libvirt_exporter/blob/9490c47c24d93cc1172560de9bed194eda77c1c6/build_static.sh#L30-L34), this was the error I was getting that led me towards this request:

```
Package libvirt was not found in the pkg-config search path.
Perhaps you should add the directory containing `libvirt.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libvirt' found
```

**Comment by bryteise** [comment]
Hello, that would be fine but I think it might be even easier for you if we were to add libvirt_exporter to a related bundle (or maybe as a standalone bundle) instead.

**Comment by bryteise** [comment]
I just looked over at the git repo and it looks like they haven't made a release yet, we could take the latest git commit but we really prefer projects that make releases.

**Comment by bswinnerton** [comment]
👋 @bryteise, thank you for the assistance on this!

> I just looked over at the git repo and it looks like they haven't made a release yet, we could take the latest git commit but we really prefer projects that make releases.

I just wrote them a proposal to support GitHub releases (or tags, even) over in https://github.com/kumina/libvirt_exporter/issues/12. We'll have to wait and see what they say.

In the mean time, what are your thoughts on adding libvirt-dev to the kvm-host bundle (or a new kvm-host-dev bundle)? That may open up possibilities for others who may want to tap into the libvirt APIs outside of the libvirt_exporter project.

**Comment by bswinnerton** [comment]
Hey @bryteise! Just wondering if you had any thoughts on my message above.

**Comment by bryteise** [comment]
Hey, thanks for the ping, too many things going on X(. In general we keep development libraries out of use case oriented bundles (outside of developer use case bundles) so I guess I'll just spin up the kvm-host-dev bundle.

**Comment by bryteise** [comment]
Should in theory be in the morning build. Hopefully we can get the exporter in when they make their release.

**Comment by bswinnerton** [comment]
Thank you so much, @bryteise!
