### ISSUE TITLE
Add HAVGED Entropy Bundle

### ISSUE THREAD

**Issue by Think7** [clearlinux/clr-bundles#75]
https://www.irisa.fr/caps/projects/hipsor/

<3

**Comment by fenrus75** [comment]
(I'l answer this as a serious request, although one could wonder if a person who wanted to be funny would also ask for this)

Hi,

so of course we will not add this. The principles behind this "entropy" are not sound; CPUs are far too 
deterministic and observable for this (with things like processor trace etc)  HOWEVER CPUs have built entropy generators that should be used instead.

If you have an actual shortage of entropy problem let us know and we can work on improving that situation.

**Comment by Think7** [comment]
It was not my intention to be funny or waste anyone’s time. 

I have run into issues on both CentOS and Ubuntu when using the Libsodium c++ crypto library. It would complain that the system did not have enough entrophy if my application performed crypto operations too soon after initial boot. Installing HAVGED solved the issue. 

Out of habit I went to install it on ClearLinux and figured it might be good to ask it be added as a bundle. I just assumed it would be an issue here also without testing. 

I apologize if my request appeared as anything other than genuine.

**Comment by fenrus75** [comment]
no problem

let us know if you see any entropy issues on Clear Linux, there should not be... but always bugs and mistunings can happen.
