### ISSUE TITLE
dbus/wifi inconsistencies

### ISSUE THREAD

**Issue by harsh-telepathy** [clearlinux/clr-bundles#77]
I noticed something curious with the latest clear release

1) WiFi speed dropped. I used to use wpa_supplicant directly in the past but now it seems to use wpa_supplicant -u, essentially relying on dbus by default and disregarding the previous config approach. wpa_cli didnt seem to be able to connect to the wpa_supplicant daemon either despite the fact it was running. That was (sorta) simple to tinker and fix (just did a systemctl disable wpa_supplicant; systemctl enable wpa_supplicant@wlan0 and created a config file in /etc/wpa_supplicant/wpa_supplicant-wlan0.conf). Also modified dhcp.service to make the Match equal 'e* wl*'. I also modified the wpa_supplicant config to explicitly use CCMP (AES). After that it generally seems faster but still not as quick as pre-upgrade. Mentioning all this here in case anyone else needs to do this.

2) The other (harder to find) issue, was with dbus. The symptoms were, when I restart the system, a simple ping to www.google.com used to take an inordinately long time to complete. Ran an strace on it and discovered it seemed to stall on the dbus device socket. If I wait (about 30 seconds) on the ping it seems to resolve itself. But if I just do a systemctl restart dbus, the ping is immediately responsive. I suspect the dbus socket isn't initialized correctly on startup and its likely tied to initialization order in systemd.

3) I have been trying to get Clear to work on a first generation (STCK1A8LFC) Intel Compute Stick (its an ideal OS for it given its lightweight and Intel optimized!). The Wifi on that one is an uber shitty realtek chipset (where the bluetooth doesnt work at all and the Wifi is very slow) so I tried to attach a USB dongle to it in an effort to get it to work faster. I noticed that the wpa_supplicant driver on Clear doesnt have wext support so my dongle doesnt work either. The original Ubuntu 14.04 that shipped with the compute stick actually supported Bluetooth and Wifi for it out of the box so I suspect Intel has the SDIO drivers for it already and just needs a recompile to get them to work. My fascination with the compute stick is, its way more powerful than any of the Raspberry Pi devices I have so it'd be epic if I got it to work completely but can understand if its a low priority bug-fix. 

4) A general problem with installation on Compute sticks (even the newest ones) is that the install only seems to support wired ethernet last I checked. I got around this but would be nice to have wifi support in the installer out of the box.

**Comment by hugleo** [comment]
2)
Slow just when boot time?
Are there enough entropy?
cat /proc/sys/kernel/random/entropy_avail

**Comment by ahkok** [comment]
Please do not file 4 issues in a single thread. It's almost impossible to work on anything this way.

**Comment by harsh-telepathy** [comment]
I agree. Actually part of the problem was I wasn't sure if points 1 and 2 were the same issue or not. Point 3 and 4 were things I wasn't too sure I wanted to waste developer time on @ Intel. They are probably very niche requirements for something like ClearLinux which is inherently targeted for cloud based deployments.

Regardless. I'll spin out 4 issues out of it.
