### ISSUE TITLE
Wireless drivers for Realtek RTL8723BE are missing

### ISSUE THREAD

**Issue by Thisuu** [clearlinux/clr-bundles#78]
Installed clear linux on a Lenovo ideapad 100 along with 'desktop' bundle and wifi card was not recognized. seems that rtl8723be drivers are missing from the 'linux-firmware-wifi' package. Bluetooth works fine.

```
thisu@clr  ~   lspci | grep Wireless
03:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8723BE PCIe Wireless Network Adapter
```

**Comment by bryteise** [comment]
Please open this under https://github.com/clearlinux/distribution/issues/, thanks!
