### ISSUE TITLE
Please add flatpak support

### ISSUE THREAD

**Issue by harsh-telepathy** [clearlinux/clr-bundles#80]
This would allow installing light desktop environments like i3 along with a few purpose driven apps (like firefox e.g.) for a nice lean configuration.

**Comment by miguelinux** [comment]
I think we can close this 

https://github.com/clearlinux/clr-bundles/commit/d7e12fb7160ec21895c7382b16dc59f4494772af

@ahkok, @bryteise

**Comment by ahkok** [comment]
We've had flatpak for a long time, but yes, with the `flatpak` bundle it should be possible to build a really small desktop using `desktop-i3` or `xfce4-desktop` or similar.
