### ISSUE TITLE
impact of removing openssh-server

### ISSUE THREAD

**Issue by shrmrf** [clearlinux/clr-bundles#82]
@bryteise I just noticed that the `openssh-server` bundle was [removed from `network-basic`](https://github.com/clearlinux/clr-bundles/commit/7e70a8105bd2d2e05636d0ced2014574026f0e1c#diff-b9d6b7622609458e799bddf45180988f)

What impact does this have on already-running systems that did not explicitly install `openssh-server` but only had `network-basic` on them? Will `openssh-server` be removed from the systems?

**Comment by bryteise** [comment]
@shrmrf this isn't fully explained in that commit but you see it removing the comment mentioning a format bump. The way this process works is that a format bump is going to involve an update to a predetermined version of Clear Linux, this means that everybody who had network-basic and not openssh-server before that update will get the included openssh-server on their system. Then the next release will remove the include but the openssh-server bundle will be installed just as if a user had added it manually on users systems. Let me know if that clears things up for you.

**Comment by shrmrf** [comment]
Thanks @bryteise for the reply.. I had this observation:

I set up a NUC today following the common install process (UEFI  etc. etc.). My USB stick was definitely a much older version. After install, I ran my setup script which installed `network-basic` but not `openssh-server` explicitly. Now, I was unable to `ssh` into the NUC. I assume that since I ran my script on a newer version of Clear, `openssh-server` never got installed.

I have 2 other test servers that have had the same script run on them. I'm wondering if `swupd update` will remove `openssh-server`?

PS complaint (not related): The update servers don't seem to be reliable today, they were unresponsive for quite a few hours.

**Comment by shrmrf** [comment]
@bryteise thanks again. I understand now. And I just noticed after your mention that it's a change from 1 year ago. 

This might not have installed `openssh-server` then because my servers are newer. I guess, however, I won't have to worry about losing `openssh-server` on my running machines and fix my script safely.

Thank you very much!
