### ISSUE TITLE
Create bundle to install a traditional package manager?

### ISSUE THREAD

**Issue by dkudriavtsev** [clearlinux/clr-bundles#9]
Is this possible in any way?

**Comment by bryteise** [comment]
So we do have yum in a bundle via os-clr-on-clr as it is used for working with the distros rpm packages so in theory you could install that bundle and add a configuration file to point to https://download.clearlinux.org/current/x86_64/os/repodata/ to do yum install of specific packages in the distro though things could go wrong in bad ways with that.

**Comment by unixbhaskar** [comment]
Why in first place yum is there?? I believe it will interfere with other stuff and it certainly not provides help. How about rip it off and do your own stuff?

The reasoning, if I have had to use the same pkg manager, then I should not use Clear Linux in the first place. Period. I personally use at least 13 different distribution from a long time...so and most of the package manager sucks and it sucks bad way. So avoid it.
YMMV

**Comment by dkudriavtsev** [comment]
@unixbhaskar `swupd`

**Comment by unixbhaskar** [comment]
Yup, I know...I am running it ..that is why I suggested discarding the other package manager on it. :)

@dkudriavtsev

**Comment by dkudriavtsev** [comment]
@unixbhaskar that is there for compatibility and build repeatability purposes AFAIK. using it might break the system and I only asked because I wanted a way to install chromium without compiling it (56GB and at least 12 hours)

**Comment by bryteise** [comment]
@unixbhaskar, yum is there for a few reasons related to building Clear Linux. It also can be handy for use cases like @dkudriavtsev described but that can be a bit more dangerous as it might conflict with a distribution provided component. Closing since I think this has been answered fully but let me know if you have any other questions.

**Comment by sirredbeard** [comment]
I found this thread and have been messing around with using yum in Clear Linux.

I wrote up a simple script and an example yum.conf [here](https://github.com/sirredbeard/yumonclearlinux).

Thanks for your work.
