### ISSUE TITLE
LVM2 package missing from storage-utils

### ISSUE THREAD

**Issue by project-phalanx** [clearlinux/clr-bundles#95]
LVM2 and LVM2-extras packages were included in storage-utils bundle. But the packages are removed with tag 27160-27170. Because of this reason, if you were using logical volume and upgrade your Clear Linux from 27150 (or older) to 27160 or 27170, your logical volumes will be disappeared.

**Comment by bryteise** [comment]
This has been reverted for 27180. We might eventually move LVM2 out of storage-utils but we'll do so in a way that won't cause breakage.
