### ISSUE TITLE
tensorflow at clearlinux is not built with mkl support

### ISSUE THREAD

**Issue by jhe33** [clearlinux/clr-bundles#98]
I installed tensorflow by swupd bundle-add, and found the performance is not good.
and checked the spec file of package tensorflow, found the build command bazel has not take --config=mkl.

meanwhile, I installed the tensorflow by anacond, the benchmark show it is much better than the one from bundle.

**Comment by fenrus75** [comment]
unfortunately MKL is not currently open source.

we are working hard to improve the open source tensorflow code, and upstream tensorflow is also integrating mkl-dnn (the open side of MKL) but for the current released version of tensorflow that did not quite work yet.

**Comment by jhe33** [comment]
https://software.intel.com/en-us/articles/intel-mkl-dnn-part-1-library-overview-and-installation

from intel MKL official site, it seems be open source now.

please check https://github.com/intel/mkl-dnn.

**Comment by fenrus75** [comment]
mkl-dnn is, mkl is not

the current released version of tensorflow does not work with mkl-dnn stand alone. the next one will, and we will absolutely be using mkl-dnn once that works

**Comment by jhe33** [comment]
ok, I just thought tensorflow only depends on mkl-dnn, because it rewrites the operator of framework.
sorry for bothering
